//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import gov.nwcg.services.ross.common_types._1.CompositeResourceRequestKeyType;
import gov.nwcg.services.ross.common_types._1.ResponseStatusType;


/**
 * Common response structdure for combination resource order operations
 * 
 * <p>Java class for CombinationResourceOrderResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CombinationResourceOrderResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseStatus" type="{http://nwcg.gov/services/ross/common_types/1.1}ResponseStatusType"/>
 *         &lt;element name="CreateIncidentResponseData" type="{http://nwcg.gov/services/ross/resource_order/1.1}CreateIncidentOperationResponseType" minOccurs="0"/>
 *         &lt;element name="ResourceRequestKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeResourceRequestKeyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CombinationResourceOrderResponseType", namespace = "http://nwcg.gov/services/ross/resource_order/1.1", propOrder = {
    "responseStatus",
    "createIncidentResponseData",
    "resourceRequestKey"
})
public class CombinationResourceOrderResponseType {

    @XmlElement(name = "ResponseStatus", required = true)
    protected ResponseStatusType responseStatus;
    @XmlElement(name = "CreateIncidentResponseData")
    protected CreateIncidentOperationResponseType createIncidentResponseData;
    @XmlElement(name = "ResourceRequestKey")
    protected CompositeResourceRequestKeyType resourceRequestKey;

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatusType }
     *     
     */
    public ResponseStatusType getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatusType }
     *     
     */
    public void setResponseStatus(ResponseStatusType value) {
        this.responseStatus = value;
    }

    public boolean isSetResponseStatus() {
        return (this.responseStatus!= null);
    }

    /**
     * Gets the value of the createIncidentResponseData property.
     * 
     * @return
     *     possible object is
     *     {@link CreateIncidentOperationResponseType }
     *     
     */
    public CreateIncidentOperationResponseType getCreateIncidentResponseData() {
        return createIncidentResponseData;
    }

    /**
     * Sets the value of the createIncidentResponseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreateIncidentOperationResponseType }
     *     
     */
    public void setCreateIncidentResponseData(CreateIncidentOperationResponseType value) {
        this.createIncidentResponseData = value;
    }

    public boolean isSetCreateIncidentResponseData() {
        return (this.createIncidentResponseData!= null);
    }

    /**
     * Gets the value of the resourceRequestKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeResourceRequestKeyType }
     *     
     */
    public CompositeResourceRequestKeyType getResourceRequestKey() {
        return resourceRequestKey;
    }

    /**
     * Sets the value of the resourceRequestKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeResourceRequestKeyType }
     *     
     */
    public void setResourceRequestKey(CompositeResourceRequestKeyType value) {
        this.resourceRequestKey = value;
    }

    public boolean isSetResourceRequestKey() {
        return (this.resourceRequestKey!= null);
    }

}
