//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.catalog._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.services.ross.catalog._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.services.ross.catalog._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteCatalogItemReq }
     * 
     */
    public DeleteCatalogItemReq createDeleteCatalogItemReq() {
        return new DeleteCatalogItemReq();
    }

    /**
     * Create an instance of {@link CreateCatalogItemReq }
     * 
     */
    public CreateCatalogItemReq createCreateCatalogItemReq() {
        return new CreateCatalogItemReq();
    }

    /**
     * Create an instance of {@link DeleteCatalogItemResp }
     * 
     */
    public DeleteCatalogItemResp createDeleteCatalogItemResp() {
        return new DeleteCatalogItemResp();
    }

    /**
     * Create an instance of {@link UpdateCatalogItemReq }
     * 
     */
    public UpdateCatalogItemReq createUpdateCatalogItemReq() {
        return new UpdateCatalogItemReq();
    }

    /**
     * Create an instance of {@link UpdateCatalogItemResp }
     * 
     */
    public UpdateCatalogItemResp createUpdateCatalogItemResp() {
        return new UpdateCatalogItemResp();
    }

    /**
     * Create an instance of {@link GetCatalogItemResp }
     * 
     */
    public GetCatalogItemResp createGetCatalogItemResp() {
        return new GetCatalogItemResp();
    }

    /**
     * Create an instance of {@link CreateCatalogItemResp }
     * 
     */
    public CreateCatalogItemResp createCreateCatalogItemResp() {
        return new CreateCatalogItemResp();
    }

    /**
     * Create an instance of {@link GetCatalogItemReq }
     * 
     */
    public GetCatalogItemReq createGetCatalogItemReq() {
        return new GetCatalogItemReq();
    }

}
