//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nwcg.gov/services/ross/catalog/1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nwcg.services.ross.catalog._1;
