SELECT 'ITEM_ID,DESCRIPTION,LTOOS_FLAG,HOPELESS,GLOBAL_INF_INV,ATM_INF_INV,EST_INF_INV,JST_INF_INV,SPR_INF_INV,PREFERRED_SUBSTITUTE,SUB_DESCRIPTIONnewLine' FROM dual;
SELECT
  (TRIM(TRAILING ' ' FROM ITM.ITEM_ID))||','||
  (REPLACE(ITM.DESCRIPTION, ',', ' '))||','||
  ITM.EXTN_LTOOS_FLAG||','||
  (TRIM(TRAILING ' ' FROM ITM.EXTN_HOPELESS_BACKORDER))||','||
  NVL(ITM.ASSUME_INFINITE_INVENTORY , 'N')||','||
  NVL(ITM.EXTN_ASSUME_INFINV_ATM, 'N')||','||
  NVL(ITM.EXTN_ASSUME_INFINV_EST, 'N')||','||
  NVL(ITM.EXTN_ASSUME_INFINV_JST, 'N')||','||
  NVL(ITM.EXTN_ASSUME_INFINV_SPR, 'N')||','||
  NVL((TRIM(TRAILING ' ' FROM ITM.EXTN_PREFERRED_SUBSTITUTE)), '')||','||
  NVL(ITMSUB.DESCRIPTION, '')||'newLine'
FROM OMCTMETA.YFS_ITEM ITM LEFT JOIN OMCTMETA.YFS_ITEM ITMSUB ON ITM.EXTN_PREFERRED_SUBSTITUTE = ITMSUB.ITEM_ID
WHERE (ITM.EXTN_LTOOS_FLAG = 'Y'
    OR ITM.EXTN_HOPELESS_BACKORDER = 'Y'
    OR ITM.EXTN_ASSUME_INFINV_ATM ='Y'
    OR ITM.EXTN_ASSUME_INFINV_EST ='Y'
    OR ITM.EXTN_ASSUME_INFINV_JST ='Y'
    OR ITM.EXTN_ASSUME_INFINV_SPR ='Y'
    OR ITM.EXTN_PREFERRED_SUBSTITUTE IS NOT NULL
    OR ITMSUB.DESCRIPTION IS NOT NULL)
    AND rownum < 10000 ORDER BY ITM.ITEM_ID;