CREATE OR REPLACE FORCE VIEW EXTN_NWCG_INCIDENT_RPT_SR_VW ("CACHE ID", "ITEM_ID", "SERIAL_NO", "PARENT_ID", "PARENT_SERIAL", "EXTN_INCIDENT_NO", "EXTN_INCIDENT_YEAR", "ORDER_NO", "RECEIPT_NO", "ORDER_TYPE", "DOCUMENT_TYPE", "TRANSACTION_TYPE", "ORDER_HEADER_KEY", "RECEIPT_HEADER_KEY", "ORDER_LINE_KEY", "RECEIPT_LINE_KEY")
AS
  SELECT NODE "CACHE ID",
    ITEM_ID,
    SERIAL_NO,
    PARENT_ITEM_ID "PARENT_ID",
    PARENT_SERIAL_NO "PARENT_SERIAL",
    INCIDENT_NO "EXTN_INCIDENT_NO",
    INCIDENT_YEAR "EXTN_INCIDENT_YEAR",
    ORDER_NO,
    RECEIPT_NO,
    ORDER_TYPE,
    DOCUMENT_TYPE,
    TRANSACTION_TYPE,
    ORDER_HEADER_KEY,
    RECEIPT_HEADER_KEY,
    ORDER_LINE_KEY,
    RECEIPT_LINE_KEY
  FROM nwcg_serial_record;