CREATE OR REPLACE FORCE VIEW EXTN_NWCG_CONSUMABLE_ITEM_VW ("REFURBED_ITEM", "TRACKABLE_ID", "CONSUMED_ITEM", "ITEM_DESCRIPTION", "UNIT_COST", "TRANS_QTY", "TRANS_AMOUNT", "CACHE_ID", "INCIDENT_NO", "TRANSACTION_NO", "INCIDENT_NAME", "incident_other_acct_code", "incident_blm_acct_code", "incident_fs_acct_code", "override_code", "INCIDENT_YEAR", "TRANSACTION_HEADER_KEY", "TRANSACTION_LINE_KEY")
AS
  SELECT
    (SELECT DISTINCT NBT.ITEM_ID
    FROM NWCG_BILLING_TRANSACTION NBT,
      NWCG_INCIDENT_ORDER C
    WHERE NBT.INCIDENT_NO         = C.INCIDENT_NO
    AND RTRIM (NBT.INCIDENT_YEAR) = C.YEAR
      --  AND RTRIM (NBT.CACHE_ID)      = RTRIM (C.PRIMARY_CACHE_ID)
    AND NBT.TRANS_TYPE           ='WO-REFURB'
    AND NBT.TRANS_QTY            > 0
    AND NBT.TRANSACTION_LINE_KEY = BT.TRANSACTION_LINE_KEY
    )"REFURBED_ITEM",
    (SELECT DISTINCT WORK_ORDER_LINE.PRIMAY_SERIAL_NO
    FROM NWCG_MASTER_WORK_ORDER WORK_ORDER,
      NWCG_MASTER_WORK_ORDER_LINE WORK_ORDER_LINE,
      NWCG_BILLING_TRANSACTION NBT,
      NWCG_INCIDENT_ORDER C
    WHERE WORK_ORDER.INCIDENT_NO                = C.INCIDENT_NO
    AND rtrim(WORK_ORDER.MASTER_WORK_ORDER_KEY) = rtrim(WORK_ORDER_LINE.MASTER_WORK_ORDER_KEY)
    AND RTRIM (WORK_ORDER.INCIDENT_YEAR)        = C.YEAR
    AND NBT.INCIDENT_NO                         = C.INCIDENT_NO
    AND RTRIM (NBT.INCIDENT_YEAR)               = C.YEAR
      --  AND RTRIM (NBT.CACHE_ID)      = RTRIM (C.PRIMARY_CACHE_ID)
    AND NBT.TRANS_TYPE                             ='WO-REFURB'
    AND NBT.TRANS_QTY                              > 0
    AND NBT.TRANSACTION_LINE_KEY                   = BT.TRANSACTION_LINE_KEY
    AND WORK_ORDER_LINE.MASTER_WORK_ORDER_LINE_KEY = BT.TRANSACTION_LINE_KEY
    AND WORK_ORDER_LINE.MASTER_WORK_ORDER_LINE_KEY = NBT.TRANSACTION_LINE_KEY
    )"TRACKABLE_ID",
    BT.ITEM_ID "CONSUMED_ITEM",
    BT.ITEM_DESCRIPTION,
    BT.UNIT_COST,
    ABS (BT.TRANS_QTY),
    ABS (BT.trans_amount),
    BT.CACHE_ID,
    BT.INCIDENT_NO,
    BT.TRANSACTION_NO,
    IO.INCIDENT_NAME,
    io.incident_other_acct_code,
    io.incident_blm_acct_code,
    io.incident_fs_acct_code,
    io.override_code,
    BT.INCIDENT_YEAR,
    BT.TRANSACTION_HEADER_KEY,
    BT.TRANSACTION_LINE_KEY
  FROM NWCG_BILLING_TRANSACTION BT,
    NWCG_INCIDENT_ORDER io
  WHERE BT.INCIDENT_NO         = io.INCIDENT_NO
  AND RTRIM (BT.INCIDENT_YEAR) = IO.YEAR
    -- AND RTRIM (BT.CACHE_ID)      = RTRIM (io.PRIMARY_CACHE_ID)
  AND BT.TRANS_TYPE            ='WO-REFURB'
  AND BT.TRANS_QTY             < 0
  AND BT.TRANSACTION_LINE_KEY IN
    (SELECT NBT.TRANSACTION_LINE_KEY
    FROM NWCG_BILLING_TRANSACTION NBT,
      NWCG_INCIDENT_ORDER C
    WHERE NBT.INCIDENT_NO         = C.INCIDENT_NO
    AND RTRIM (NBT.INCIDENT_YEAR) = C.YEAR
      -- AND RTRIM (NBT.CACHE_ID)      = RTRIM (C.PRIMARY_CACHE_ID)
    AND NBT.TRANS_TYPE ='WO-REFURB'
    AND NBT.TRANS_QTY  > 0
    );