//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order_notification._1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.nwcg.services.ross.common_types._1.ApplicationSystemType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SystemOfOrigin" type="{http://nwcg.gov/services/ross/common_types/1.1}ApplicationSystemType"/>
 *         &lt;element name="MaxRecordsToReturn" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systemOfOrigin",
    "maxRecordsToReturn"
})
@XmlRootElement(name = "GetNotificationsReq")
public class GetNotificationsReq {

    @XmlElement(name = "SystemOfOrigin", required = true)
    protected ApplicationSystemType systemOfOrigin;
    @XmlElement(name = "MaxRecordsToReturn", defaultValue = "25")
    protected BigInteger maxRecordsToReturn;

    /**
     * Gets the value of the systemOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationSystemType }
     *     
     */
    public ApplicationSystemType getSystemOfOrigin() {
        return systemOfOrigin;
    }

    /**
     * Sets the value of the systemOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationSystemType }
     *     
     */
    public void setSystemOfOrigin(ApplicationSystemType value) {
        this.systemOfOrigin = value;
    }

    public boolean isSetSystemOfOrigin() {
        return (this.systemOfOrigin!= null);
    }

    /**
     * Gets the value of the maxRecordsToReturn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxRecordsToReturn() {
        return maxRecordsToReturn;
    }

    /**
     * Sets the value of the maxRecordsToReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxRecordsToReturn(BigInteger value) {
        this.maxRecordsToReturn = value;
    }

    public boolean isSetMaxRecordsToReturn() {
        return (this.maxRecordsToReturn!= null);
    }

}
