CREATE OR REPLACE FORCE VIEW EXTN_NWCG_LOSS_USE_RPT_VW ("ITEM_ID", "CLASS", "ITEM_DESCRIPTION", "UOM", "UNIT_PRICE", "QTY_AS_ITEM", "QTY_REFURB", "QTY_AS_KITS", "TRANSFER_IN", "TRANSFERRED_IN_AS_KITS", "PARTS_USED", "RCD_ITEMS", "RCD_AS_KITS", "RCD_IN_KITS", "TRANSFER_OUT", "TRANSFERRED_OUT_AS_KITS", "QTY_WO", "QTY_UNSER", "QTY_RFIREFURB", "QTY_UNSREFURB", "QTY_UNSNWT_REFURB", "QTY_UNSER_NWT", "EXTN_CACHE_SHIP_ACCT_CODE", "SA_OVERRIDE_CODE", "INCIDENT NO", "EXTN_INCIDENT_NAME", "OTHER ACCT CODE", "BLM ACCT CODE", "FS ACCT CODE", "EXTN_OVERRIDE_CODE", "YEAR", "CACHE ID")
AS
  SELECT item_id,
    class,
    item_description,
    uom,
    unit_price,
    qty_as_item,
    qty_refurb,
    SUM(qty_as_kits) "QTY_AS_KITS",
    transfer_in,
    SUM(transferred_in_as_kits) "TRANSFERRED_IN_AS_KITS",
    parts_used,
    rcd_items,
    SUM(rcd_as_kits) "RCD_AS_KITS",
    SUM(rcd_in_kits) "RCD_IN_KITS",
    transfer_out,
    SUM(transferred_out_as_kits) "TRANSFERRED_OUT_AS_KITS",
    qty_wo,
    qty_unser,
    qty_rfirefurb,
    qty_unsrefurb,
    qty_unsnwt_refurb,
    qty_unser_nwt,
    extn_cache_ship_acct_code,
    sa_override_code,
    "INCIDENT NO",
    extn_incident_name,
    "OTHER ACCT CODE",
    "BLM ACCT CODE",
    "FS ACCT CODE",
    extn_override_code,
    YEAR,
    "CACHE ID"
  FROM EXTN_NWCG_INCIDENT_RPT_PRE_VW
  GROUP BY item_id,
    class,
    item_description,
    uom,
    unit_price,
    qty_as_item,
    qty_refurb,
    transfer_in,
    parts_used,
    rcd_items,
    transfer_out,
    qty_wo,
    qty_unser,
    qty_rfirefurb,
    qty_unsrefurb,
    qty_unsnwt_refurb,
    qty_unser_nwt,
    extn_cache_ship_acct_code,
    sa_override_code,
    "INCIDENT NO",
    extn_incident_name,
    "OTHER ACCT CODE",
    "BLM ACCT CODE",
    "FS ACCT CODE",
    extn_override_code,
    YEAR,
    "CACHE ID";