CREATE OR REPLACE FORCE VIEW EXTN_NWCG_BILLING_INFO_RPT_VW ("TRANS_DATE", "TRANS_TYPE", "DOCUMENT_TYPE", "TRANSACTION NO", "INCIDENT NO", "INCIDENT YEAR", "INCIDENT_NAME", "ITEM_ID", "ITEM_DESCRIPTION", "TRANS_QTY", "UNIT_COST", "TRANS_AMOUNT", "IS_ACCOUNT_SPLIT", "BLM ACCT CODE", "FS ACCT CODE", "INCIDENT_FS_OVERRIDE_CODE", "OTHER ACCT CODE", "CACHE ID", "IS_EXTRACTED", "IS_REVIEWED", "EXTN_CUSTOMER_NAME", "BILL_TO_FIRST_NAME", "BILL_TO_MIDDLE_NAME", "BILL_TO_LAST_NAME", "BILL_TO_ADDRESS1", "BILL_TO_ADDRESS2", "BILL_TO_ADDRESS3", "BILL_TO_ADDRESS4", "BILL_TO_ADDRESS5", "BILL_TO_ADDRESS6", "BILL_TO_CITY", "BILL_TO_STATE", "BILL_TO_COUNTRY", "BILL_TO_DAY_FAX_NO", "BILL_TO_DAY_PHONE", "BILL_TO_ZIP_CODE", "FIRST_NAME", "MIDDLE_NAME", "LAST_NAME", "ADDRESS_LINE1", "ADDRESS_LINE2", "ADDRESS_LINE3", "ADDRESS_LINE4", "ADDRESS_LINE5", "ADDRESS_LINE6", "CITY", "STATE", "COUNTRY", "DAY_FAX_NO", "DAY_PHONE", "ZIP_CODE", "CACHE_NAME")
AS
  SELECT a.trans_date,
    a.trans_type,
    a.document_type,
    a.transaction_no "TRANSACTION NO",
    a.incident_no "INCIDENT NO",
    a.incident_year "INCIDENT YEAR",
    a.incident_name,
    a.item_id,
    a.item_description,
    a.trans_qty,
    a.unit_cost,
    a.trans_amount,
    a.is_account_split,
    a.incident_blm_acct_code "BLM ACCT CODE",
    a.incident_fs_acct_code "FS ACCT CODE",
    a.incident_fs_override_code,
    a.incident_other_acct_code "OTHER ACCT CODE",
    a.cache_id "CACHE ID",
    a.is_extracted,
    a.is_reviewed,
    b.customer_name "EXTN_CUSTOMER_NAME",
    c.first_name "BILL_TO_FIRST_NAME",
    c.middle_name "BILL_TO_MIDDLE_NAME",
    c.last_name "BILL_TO_LAST_NAME",
    c.address_line1 "BILL_TO_ADDRESS1",
    c.address_line2 "BILL_TO_ADDRESS2",
    c.address_line3 "BILL_TO_ADDRESS3",
    c.address_line4 "BILL_TO_ADDRESS4",
    c.address_line5 "BILL_TO_ADDRESS5",
    c.address_line6 "BILL_TO_ADDRESS6",
    c.city "BILL_TO_CITY",
    c.state "BILL_TO_STATE",
    c.country "BILL_TO_COUNTRY",
    c.day_fax_no "BILL_TO_DAY_FAX_NO",
    c.day_phone "BILL_TO_DAY_PHONE",
    c.zip_code "BILL_TO_ZIP_CODE",
    d.first_name,
    d.middle_name,
    d.last_name,
    d.address_line1,
    d.address_line2,
    d.address_line3,
    d.address_line4,
    d.address_line5,
    d.address_line6,
    d.city,
    d.state,
    d.country,
    d.day_fax_no,
    d.day_phone,
    d.zip_code,
    e.organization_name "CACHE_NAME"
  FROM nwcg_billing_transaction a,
    nwcg_incident_order b,
    yfs_person_info c,
    yfs_person_info d,
    yfs_organization e
    --where a.document_type in ('0001','0006','0007.ex','0008.ex')
  WHERE a.incident_no          = b.incident_no
  AND a.incident_year          = b.year
  AND b.person_info_billto_key = c.person_info_key
  AND rtrim(a.cache_id)        = rtrim(e.organization_code)
  AND e.contact_address_key    = d.person_info_key;