//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order_notification._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.nwcg.services.ross.common_types._1.CompositeIncidentKeyType;
import gov.nwcg.services.ross.common_types._1.IncidentReturnType;
import gov.nwcg.services.ross.common_types._1.NotificationBaseType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NotificationBase" type="{http://nwcg.gov/services/ross/common_types/1.1}NotificationBaseType"/>
 *         &lt;element name="SourceIncidentKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeIncidentKeyType"/>
 *         &lt;element name="SourceIncident" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentReturnType"/>
 *         &lt;element name="DestinationIncidentKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeIncidentKeyType"/>
 *         &lt;element name="DestinationIncident" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentReturnType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notificationBase",
    "sourceIncidentKey",
    "sourceIncident",
    "destinationIncidentKey",
    "destinationIncident"
})
@XmlRootElement(name = "MergeIncidentNotification")
public class MergeIncidentNotification {

    @XmlElement(name = "NotificationBase", required = true)
    protected NotificationBaseType notificationBase;
    @XmlElement(name = "SourceIncidentKey", required = true)
    protected CompositeIncidentKeyType sourceIncidentKey;
    @XmlElement(name = "SourceIncident", required = true)
    protected IncidentReturnType sourceIncident;
    @XmlElement(name = "DestinationIncidentKey", required = true)
    protected CompositeIncidentKeyType destinationIncidentKey;
    @XmlElement(name = "DestinationIncident", required = true)
    protected IncidentReturnType destinationIncident;

    /**
     * Gets the value of the notificationBase property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationBaseType }
     *     
     */
    public NotificationBaseType getNotificationBase() {
        return notificationBase;
    }

    /**
     * Sets the value of the notificationBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationBaseType }
     *     
     */
    public void setNotificationBase(NotificationBaseType value) {
        this.notificationBase = value;
    }

    public boolean isSetNotificationBase() {
        return (this.notificationBase!= null);
    }

    /**
     * Gets the value of the sourceIncidentKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public CompositeIncidentKeyType getSourceIncidentKey() {
        return sourceIncidentKey;
    }

    /**
     * Sets the value of the sourceIncidentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public void setSourceIncidentKey(CompositeIncidentKeyType value) {
        this.sourceIncidentKey = value;
    }

    public boolean isSetSourceIncidentKey() {
        return (this.sourceIncidentKey!= null);
    }

    /**
     * Gets the value of the sourceIncident property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentReturnType }
     *     
     */
    public IncidentReturnType getSourceIncident() {
        return sourceIncident;
    }

    /**
     * Sets the value of the sourceIncident property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentReturnType }
     *     
     */
    public void setSourceIncident(IncidentReturnType value) {
        this.sourceIncident = value;
    }

    public boolean isSetSourceIncident() {
        return (this.sourceIncident!= null);
    }

    /**
     * Gets the value of the destinationIncidentKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public CompositeIncidentKeyType getDestinationIncidentKey() {
        return destinationIncidentKey;
    }

    /**
     * Sets the value of the destinationIncidentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public void setDestinationIncidentKey(CompositeIncidentKeyType value) {
        this.destinationIncidentKey = value;
    }

    public boolean isSetDestinationIncidentKey() {
        return (this.destinationIncidentKey!= null);
    }

    /**
     * Gets the value of the destinationIncident property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentReturnType }
     *     
     */
    public IncidentReturnType getDestinationIncident() {
        return destinationIncident;
    }

    /**
     * Sets the value of the destinationIncident property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentReturnType }
     *     
     */
    public void setDestinationIncident(IncidentReturnType value) {
        this.destinationIncident = value;
    }

    public boolean isSetDestinationIncident() {
        return (this.destinationIncident!= null);
    }

}
