//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order_notification._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import gov.nwcg.services.ross.common_types._1.ApplicationSystemType;
import gov.nwcg.services.ross.common_types._1.ResourceRequestOperationNotificationType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.services.ross.resource_order_notification._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeliverNotificationReqNotifiedSystem_QNAME = new QName("http://nwcg.gov/services/ross/resource_order_notification/1.1", "NotifiedSystem");
    private final static QName _ResourceRequestOperationNotification_QNAME = new QName("http://nwcg.gov/services/ross/resource_order_notification/1.1", "ResourceRequestOperationNotification");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.services.ross.resource_order_notification._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateIncidentRadioFrequencyDetailsNotification }
     * 
     */
    public UpdateIncidentRadioFrequencyDetailsNotification createUpdateIncidentRadioFrequencyDetailsNotification() {
        return new UpdateIncidentRadioFrequencyDetailsNotification();
    }

    /**
     * Create an instance of {@link UpdateIncidentNotification }
     * 
     */
    public UpdateIncidentNotification createUpdateIncidentNotification() {
        return new UpdateIncidentNotification();
    }

    /**
     * Create an instance of {@link DeleteIncidentAviationHazardNotification }
     * 
     */
    public DeleteIncidentAviationHazardNotification createDeleteIncidentAviationHazardNotification() {
        return new DeleteIncidentAviationHazardNotification();
    }

    /**
     * Create an instance of {@link AddIncidentDocumentationNotification }
     * 
     */
    public AddIncidentDocumentationNotification createAddIncidentDocumentationNotification() {
        return new AddIncidentDocumentationNotification();
    }

    /**
     * Create an instance of {@link TransferIncidentNotification }
     * 
     */
    public TransferIncidentNotification createTransferIncidentNotification() {
        return new TransferIncidentNotification();
    }

    /**
     * Create an instance of {@link MergeIncidentNotification }
     * 
     */
    public MergeIncidentNotification createMergeIncidentNotification() {
        return new MergeIncidentNotification();
    }

    /**
     * Create an instance of {@link DeliverNotificationResp }
     * 
     */
    public DeliverNotificationResp createDeliverNotificationResp() {
        return new DeliverNotificationResp();
    }

    /**
     * Create an instance of {@link UpdateResourceRequestDetailsNotification }
     * 
     */
    public UpdateResourceRequestDetailsNotification createUpdateResourceRequestDetailsNotification() {
        return new UpdateResourceRequestDetailsNotification();
    }

    /**
     * Create an instance of {@link GetNotificationsResp.NotificationMessages.NotificationMessage }
     * 
     */
    public GetNotificationsResp.NotificationMessages.NotificationMessage createGetNotificationsRespNotificationMessagesNotificationMessage() {
        return new GetNotificationsResp.NotificationMessages.NotificationMessage();
    }

    /**
     * Create an instance of {@link UpdateIncidentKeyNotification }
     * 
     */
    public UpdateIncidentKeyNotification createUpdateIncidentKeyNotification() {
        return new UpdateIncidentKeyNotification();
    }

    /**
     * Create an instance of {@link UpdateIncidentRadioFrequencyKeyNotification }
     * 
     */
    public UpdateIncidentRadioFrequencyKeyNotification createUpdateIncidentRadioFrequencyKeyNotification() {
        return new UpdateIncidentRadioFrequencyKeyNotification();
    }

    /**
     * Create an instance of {@link DeleteIncidentRadioFrequencyNotification }
     * 
     */
    public DeleteIncidentRadioFrequencyNotification createDeleteIncidentRadioFrequencyNotification() {
        return new DeleteIncidentRadioFrequencyNotification();
    }

    /**
     * Create an instance of {@link UpdateIncidentAviationHazardDetailsNotification }
     * 
     */
    public UpdateIncidentAviationHazardDetailsNotification createUpdateIncidentAviationHazardDetailsNotification() {
        return new UpdateIncidentAviationHazardDetailsNotification();
    }

    /**
     * Create an instance of {@link GetNotificationsResp.NotificationMessages }
     * 
     */
    public GetNotificationsResp.NotificationMessages createGetNotificationsRespNotificationMessages() {
        return new GetNotificationsResp.NotificationMessages();
    }

    /**
     * Create an instance of {@link CreateResourceRequestNotification }
     * 
     */
    public CreateResourceRequestNotification createCreateResourceRequestNotification() {
        return new CreateResourceRequestNotification();
    }

    /**
     * Create an instance of {@link CreateIncidentNotification }
     * 
     */
    public CreateIncidentNotification createCreateIncidentNotification() {
        return new CreateIncidentNotification();
    }

    /**
     * Create an instance of {@link AddIncidentAviationHazardNotification }
     * 
     */
    public AddIncidentAviationHazardNotification createAddIncidentAviationHazardNotification() {
        return new AddIncidentAviationHazardNotification();
    }

    /**
     * Create an instance of {@link DeliverNotificationReq }
     * 
     */
    public DeliverNotificationReq createDeliverNotificationReq() {
        return new DeliverNotificationReq();
    }

    /**
     * Create an instance of {@link PlaceResourceRequestNotification }
     * 
     */
    public PlaceResourceRequestNotification createPlaceResourceRequestNotification() {
        return new PlaceResourceRequestNotification();
    }

    /**
     * Create an instance of {@link AddIncidentRadioFrequencyNotification }
     * 
     */
    public AddIncidentRadioFrequencyNotification createAddIncidentRadioFrequencyNotification() {
        return new AddIncidentRadioFrequencyNotification();
    }

    /**
     * Create an instance of {@link GetNotificationsResp }
     * 
     */
    public GetNotificationsResp createGetNotificationsResp() {
        return new GetNotificationsResp();
    }

    /**
     * Create an instance of {@link ResourceRequestReassignNotification }
     * 
     */
    public ResourceRequestReassignNotification createResourceRequestReassignNotification() {
        return new ResourceRequestReassignNotification();
    }

    /**
     * Create an instance of {@link GetNotificationsReq }
     * 
     */
    public GetNotificationsReq createGetNotificationsReq() {
        return new GetNotificationsReq();
    }

    /**
     * Create an instance of {@link UpdateIncidentDetailsNotification }
     * 
     */
    public UpdateIncidentDetailsNotification createUpdateIncidentDetailsNotification() {
        return new UpdateIncidentDetailsNotification();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationSystemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order_notification/1.1", name = "NotifiedSystem", scope = DeliverNotificationReq.class)
    public JAXBElement<ApplicationSystemType> createDeliverNotificationReqNotifiedSystem(ApplicationSystemType value) {
        return new JAXBElement<ApplicationSystemType>(_DeliverNotificationReqNotifiedSystem_QNAME, ApplicationSystemType.class, DeliverNotificationReq.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceRequestOperationNotificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order_notification/1.1", name = "ResourceRequestOperationNotification")
    public JAXBElement<ResourceRequestOperationNotificationType> createResourceRequestOperationNotification(ResourceRequestOperationNotificationType value) {
        return new JAXBElement<ResourceRequestOperationNotificationType>(_ResourceRequestOperationNotification_QNAME, ResourceRequestOperationNotificationType.class, null, value);
    }

}
