//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order_notification._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import gov.nwcg.services.ross.common_types._1.CompositeIncidentKeyType;
import gov.nwcg.services.ross.common_types._1.NotificationBaseType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NotificationBase" type="{http://nwcg.gov/services/ross/common_types/1.1}NotificationBaseType"/>
 *         &lt;element name="OldIncidentKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeIncidentKeyType"/>
 *         &lt;element name="NewIncidentKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeIncidentKeyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "notificationBase",
    "oldIncidentKey",
    "newIncidentKey"
})
@XmlRootElement(name = "UpdateIncidentKeyNotification")
public class UpdateIncidentKeyNotification {

    @XmlElement(name = "NotificationBase", required = true)
    protected NotificationBaseType notificationBase;
    @XmlElement(name = "OldIncidentKey", required = true)
    protected CompositeIncidentKeyType oldIncidentKey;
    @XmlElement(name = "NewIncidentKey", required = true)
    protected CompositeIncidentKeyType newIncidentKey;

    /**
     * Gets the value of the notificationBase property.
     * 
     * @return
     *     possible object is
     *     {@link NotificationBaseType }
     *     
     */
    public NotificationBaseType getNotificationBase() {
        return notificationBase;
    }

    /**
     * Sets the value of the notificationBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotificationBaseType }
     *     
     */
    public void setNotificationBase(NotificationBaseType value) {
        this.notificationBase = value;
    }

    public boolean isSetNotificationBase() {
        return (this.notificationBase!= null);
    }

    /**
     * Gets the value of the oldIncidentKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public CompositeIncidentKeyType getOldIncidentKey() {
        return oldIncidentKey;
    }

    /**
     * Sets the value of the oldIncidentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public void setOldIncidentKey(CompositeIncidentKeyType value) {
        this.oldIncidentKey = value;
    }

    public boolean isSetOldIncidentKey() {
        return (this.oldIncidentKey!= null);
    }

    /**
     * Gets the value of the newIncidentKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public CompositeIncidentKeyType getNewIncidentKey() {
        return newIncidentKey;
    }

    /**
     * Sets the value of the newIncidentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public void setNewIncidentKey(CompositeIncidentKeyType value) {
        this.newIncidentKey = value;
    }

    public boolean isSetNewIncidentKey() {
        return (this.newIncidentKey!= null);
    }

}
