//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order.wsdl._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import gov.nwcg.services.ross.resource_order._1.DeliverOperationResultsReq;
import gov.nwcg.services.ross.resource_order._1.DeliverOperationResultsResp;
import gov.nwcg.services.ross.resource_order_notification._1.DeliverNotificationReq;
import gov.nwcg.services.ross.resource_order_notification._1.DeliverNotificationResp;

@WebService(name = "DeliveryInterface", targetNamespace = "http://nwcg.gov/services/ross/resource_order/wsdl/1.1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DeliveryInterface {


    /**
     * 
     * @param body
     * @return
     *     returns gov.nwcg.services.ross.resource_order._1.DeliverOperationResultsResp
     */
    @WebMethod(operationName = "DeliverOperationResult", action = "DeliverOperationResult")
    @WebResult(name = "DeliverOperationResultsResp", targetNamespace = "http://nwcg.gov/services/ross/resource_order/1.1", partName = "body")
    public DeliverOperationResultsResp deliverOperationResult(
        @WebParam(name = "DeliverOperationResultsReq", targetNamespace = "http://nwcg.gov/services/ross/resource_order/1.1", partName = "body")
        DeliverOperationResultsReq body);

    /**
     * 
     * @param body
     * @return
     *     returns gov.nwcg.services.ross.resource_order_notification._1.DeliverNotificationResp
     */
    @WebMethod(operationName = "DeliverNotification", action = "DeliverNotificationt")
    @WebResult(name = "DeliverNotificationResp", targetNamespace = "http://nwcg.gov/services/ross/resource_order_notification/1.1", partName = "body")
    public DeliverNotificationResp deliverNotification(
        @WebParam(name = "DeliverNotificationReq", targetNamespace = "http://nwcg.gov/services/ross/resource_order_notification/1.1", partName = "body")
        DeliverNotificationReq body);

}
