//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order.wsdl._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.services.ross.resource_order.wsdl._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.services.ross.resource_order.wsdl._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateNFESResourceRequestResponse }
     * 
     */
    public UpdateNFESResourceRequestResponse createUpdateNFESResourceRequestResponse() {
        return new UpdateNFESResourceRequestResponse();
    }

    /**
     * Create an instance of {@link UpdateNFESResourceRequest }
     * 
     */
    public UpdateNFESResourceRequest createUpdateNFESResourceRequest() {
        return new UpdateNFESResourceRequest();
    }

}
