//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * User account information
 * 
 * <p>Java class for AccessUserAccountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessUserAccountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UserName" type="{http://nwcg.gov/services/ross/common_types/1.1}AccountUserNameSimpleType"/>
 *         &lt;element name="AccountManagerDispatch" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType"/>
 *         &lt;element name="AccessAddedInd" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="AffectedDispatch" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType"/>
 *         &lt;element name="Password" type="{http://nwcg.gov/services/ross/common_types/1.1}AccountPasswordSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessUserAccountType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "userName",
    "accountManagerDispatch",
    "accessAddedInd",
    "affectedDispatch",
    "password"
})
public class AccessUserAccountType {

    @XmlElement(name = "UserName", required = true)
    protected String userName;
    @XmlElement(name = "AccountManagerDispatch", required = true)
    protected UnitIDType accountManagerDispatch;
    @XmlElement(name = "AccessAddedInd")
    protected boolean accessAddedInd;
    @XmlElement(name = "AffectedDispatch", required = true)
    protected UnitIDType affectedDispatch;
    @XmlElement(name = "Password")
    protected String password;

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    public boolean isSetUserName() {
        return (this.userName!= null);
    }

    /**
     * Gets the value of the accountManagerDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getAccountManagerDispatch() {
        return accountManagerDispatch;
    }

    /**
     * Sets the value of the accountManagerDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setAccountManagerDispatch(UnitIDType value) {
        this.accountManagerDispatch = value;
    }

    public boolean isSetAccountManagerDispatch() {
        return (this.accountManagerDispatch!= null);
    }

    /**
     * Gets the value of the accessAddedInd property.
     * 
     */
    public boolean isAccessAddedInd() {
        return accessAddedInd;
    }

    /**
     * Sets the value of the accessAddedInd property.
     * 
     */
    public void setAccessAddedInd(boolean value) {
        this.accessAddedInd = value;
    }

    public boolean isSetAccessAddedInd() {
        return true;
    }

    /**
     * Gets the value of the affectedDispatch property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getAffectedDispatch() {
        return affectedDispatch;
    }

    /**
     * Sets the value of the affectedDispatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setAffectedDispatch(UnitIDType value) {
        this.affectedDispatch = value;
    }

    public boolean isSetAffectedDispatch() {
        return (this.affectedDispatch!= null);
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    public boolean isSetPassword() {
        return (this.password!= null);
    }

}
