//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResponseStatus" type="{http://nwcg.gov/services/ross/common_types/1.1}ResponseStatusType"/>
 *         &lt;element name="Username">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IsAuthenticatedIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="userFullname" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="authenticationMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseStatus",
    "username",
    "isAuthenticatedIndicator",
    "userFullname",
    "authenticationMessage"
})
@XmlRootElement(name = "AuthUserResp")
public class AuthUserResp {

    @XmlElement(name = "ResponseStatus", required = true)
    protected ResponseStatusType responseStatus;
    @XmlElement(name = "Username", required = true)
    protected String username;
    @XmlElement(name = "IsAuthenticatedIndicator")
    protected boolean isAuthenticatedIndicator;
    protected String userFullname;
    protected String authenticationMessage;

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseStatusType }
     *     
     */
    public ResponseStatusType getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseStatusType }
     *     
     */
    public void setResponseStatus(ResponseStatusType value) {
        this.responseStatus = value;
    }

    public boolean isSetResponseStatus() {
        return (this.responseStatus!= null);
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    public boolean isSetUsername() {
        return (this.username!= null);
    }

    /**
     * Gets the value of the isAuthenticatedIndicator property.
     * 
     */
    public boolean isIsAuthenticatedIndicator() {
        return isAuthenticatedIndicator;
    }

    /**
     * Sets the value of the isAuthenticatedIndicator property.
     * 
     */
    public void setIsAuthenticatedIndicator(boolean value) {
        this.isAuthenticatedIndicator = value;
    }

    public boolean isSetIsAuthenticatedIndicator() {
        return true;
    }

    /**
     * Gets the value of the userFullname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFullname() {
        return userFullname;
    }

    /**
     * Sets the value of the userFullname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFullname(String value) {
        this.userFullname = value;
    }

    public boolean isSetUserFullname() {
        return (this.userFullname!= null);
    }

    /**
     * Gets the value of the authenticationMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationMessage() {
        return authenticationMessage;
    }

    /**
     * Sets the value of the authenticationMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationMessage(String value) {
        this.authenticationMessage = value;
    }

    public boolean isSetAuthenticationMessage() {
        return (this.authenticationMessage!= null);
    }

}
