//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Catalog item data
 * 
 * <p>Java class for CatalogItemCreateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogItemCreateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogType" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogTypeSimpleType"/>
 *         &lt;element name="CatalogItemName" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemDescriptionSimpleType"/>
 *         &lt;element name="CatalogItemCode" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemMnemonicSimpleType" minOccurs="0"/>
 *         &lt;element name="TrackingRequiredInd" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="OrderableWithQuantityInd" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UnitOfIssue" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitOfIssueSimpleType" minOccurs="0"/>
 *         &lt;element name="StandardPack" type="{http://nwcg.gov/services/ross/common_types/1.1}StandardPackSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogItemCreateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "catalogType",
    "catalogItemName",
    "catalogItemCode",
    "trackingRequiredInd",
    "orderableWithQuantityInd",
    "unitOfIssue",
    "standardPack"
})
public class CatalogItemCreateType {

    @XmlElement(name = "CatalogType", required = true)
    protected CatalogTypeSimpleType catalogType;
    @XmlElement(name = "CatalogItemName", required = true)
    protected String catalogItemName;
    @XmlElement(name = "CatalogItemCode")
    protected String catalogItemCode;
    @XmlElement(name = "TrackingRequiredInd")
    protected boolean trackingRequiredInd;
    @XmlElement(name = "OrderableWithQuantityInd")
    protected boolean orderableWithQuantityInd;
    @XmlElement(name = "UnitOfIssue")
    protected String unitOfIssue;
    @XmlElement(name = "StandardPack")
    protected String standardPack;

    /**
     * Gets the value of the catalogType property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogTypeSimpleType }
     *     
     */
    public CatalogTypeSimpleType getCatalogType() {
        return catalogType;
    }

    /**
     * Sets the value of the catalogType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogTypeSimpleType }
     *     
     */
    public void setCatalogType(CatalogTypeSimpleType value) {
        this.catalogType = value;
    }

    public boolean isSetCatalogType() {
        return (this.catalogType!= null);
    }

    /**
     * Gets the value of the catalogItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemName() {
        return catalogItemName;
    }

    /**
     * Sets the value of the catalogItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemName(String value) {
        this.catalogItemName = value;
    }

    public boolean isSetCatalogItemName() {
        return (this.catalogItemName!= null);
    }

    /**
     * Gets the value of the catalogItemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemCode() {
        return catalogItemCode;
    }

    /**
     * Sets the value of the catalogItemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemCode(String value) {
        this.catalogItemCode = value;
    }

    public boolean isSetCatalogItemCode() {
        return (this.catalogItemCode!= null);
    }

    /**
     * Gets the value of the trackingRequiredInd property.
     * 
     */
    public boolean isTrackingRequiredInd() {
        return trackingRequiredInd;
    }

    /**
     * Sets the value of the trackingRequiredInd property.
     * 
     */
    public void setTrackingRequiredInd(boolean value) {
        this.trackingRequiredInd = value;
    }

    public boolean isSetTrackingRequiredInd() {
        return true;
    }

    /**
     * Gets the value of the orderableWithQuantityInd property.
     * 
     */
    public boolean isOrderableWithQuantityInd() {
        return orderableWithQuantityInd;
    }

    /**
     * Sets the value of the orderableWithQuantityInd property.
     * 
     */
    public void setOrderableWithQuantityInd(boolean value) {
        this.orderableWithQuantityInd = value;
    }

    public boolean isSetOrderableWithQuantityInd() {
        return true;
    }

    /**
     * Gets the value of the unitOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfIssue() {
        return unitOfIssue;
    }

    /**
     * Sets the value of the unitOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfIssue(String value) {
        this.unitOfIssue = value;
    }

    public boolean isSetUnitOfIssue() {
        return (this.unitOfIssue!= null);
    }

    /**
     * Gets the value of the standardPack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardPack() {
        return standardPack;
    }

    /**
     * Sets the value of the standardPack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardPack(String value) {
        this.standardPack = value;
    }

    public boolean isSetStandardPack() {
        return (this.standardPack!= null);
    }

}
