//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  2.6 -Catalog Item structure
 * 
 * <p>Java class for CatalogItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogType" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogTypeSimpleType"/>
 *         &lt;element name="CatalogName" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogSimpleType"/>
 *         &lt;element name="CatalogItemDescription" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemDescriptionSimpleType"/>       
 *         &lt;element name="CatalogItemMnemonic" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemMnemonicSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogItemType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "catalogType",
    "catalogName",
    "catalogItemDescription",
    "catalogItemMnemonic"
})
public class CatalogItemType {

    @XmlElement(name = "CatalogType", required = true)
    protected CatalogTypeSimpleType catalogType;
    @XmlElement(name = "CatalogName", required = true)
    protected CatalogSimpleType catalogName;
    @XmlElement(name = "CatalogItemDescription", required = true)
    protected String catalogItemDescription;
    @XmlElement(name = "CatalogItemMnemonic")
    protected String catalogItemMnemonic;

    /**
     * Gets the value of the catalogType property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogTypeSimpleType }
     *     
     */
    public CatalogTypeSimpleType getCatalogType() {
        return catalogType;
    }

    /**
     * Sets the value of the catalogType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogTypeSimpleType }
     *     
     */
    public void setCatalogType(CatalogTypeSimpleType value) {
        this.catalogType = value;
    }

    public boolean isSetCatalogType() {
        return (this.catalogType!= null);
    }

    /**
     * Gets the value of the catalogName property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogSimpleType }
     *     
     */
    public CatalogSimpleType getCatalogName() {
        return catalogName;
    }

    /**
     * Sets the value of the catalogName property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogSimpleType }
     *     
     */
    public void setCatalogName(CatalogSimpleType value) {
        this.catalogName = value;
    }

    public boolean isSetCatalogName() {
        return (this.catalogName!= null);
    }

    /**
     * Gets the value of the catalogItemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemDescription() {
        return catalogItemDescription;
    }

    /**
     * Sets the value of the catalogItemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemDescription(String value) {
        this.catalogItemDescription = value;
    }

    public boolean isSetCatalogItemDescription() {
        return (this.catalogItemDescription!= null);
    }
    
    /**
     * Gets the value of the catalogItemMnemonic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemMnemonic() {
        return catalogItemMnemonic;
    }

    /**
     * Sets the value of the catalogItemMnemonic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemMnemonic(String value) {
        this.catalogItemMnemonic = value;
    }

    public boolean isSetCatalogItemMnemonic() {
        return (this.catalogItemMnemonic!= null);
    }

}
