//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CatalogSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CatalogSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Aircraft"/>
 *     &lt;enumeration value="Person"/>
 *     &lt;enumeration value="Crew"/>
 *     &lt;enumeration value="Team"/>
 *     &lt;enumeration value="Equipment"/>
 *     &lt;enumeration value="Supply"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
@XmlType(name = "CatalogSimpleType", namespace = "http://nwcg.gov/services/ross/common_types/1.1")
public enum CatalogSimpleType {

    @XmlEnumValue("Aircraft")
    AIRCRAFT("Aircraft"),
    @XmlEnumValue("Person")
    PERSON("Person"),
    @XmlEnumValue("Crew")
    CREW("Crew"),
    @XmlEnumValue("Team")
    TEAM("Team"),
    @XmlEnumValue("Equipment")
    EQUIPMENT("Equipment"),
    @XmlEnumValue("Supply")
    SUPPLY("Supply");
    private final String value;

    CatalogSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CatalogSimpleType fromValue(String v) {
        for (CatalogSimpleType c: CatalogSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
