//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing Key information referring to a specific resource request across the ROSS Services Interface
 * 
 * <p>Java class for CompositeResourceRequestKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompositeResourceRequestKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceRequestID" type="{http://nwcg.gov/services/ross/common_types/1.1}IDType" minOccurs="0"/>
 *         &lt;element name="NaturalResourceRequestKey" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestNaturalKeyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositeResourceRequestKeyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "resourceRequestID",
    "naturalResourceRequestKey"
})
public class CompositeResourceRequestKeyType {

    @XmlElement(name = "ResourceRequestID")
    protected IDType resourceRequestID;
    @XmlElement(name = "NaturalResourceRequestKey", required = true)
    protected ResourceRequestNaturalKeyType naturalResourceRequestKey;

    /**
     * Gets the value of the resourceRequestID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getResourceRequestID() {
        return resourceRequestID;
    }

    /**
     * Sets the value of the resourceRequestID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setResourceRequestID(IDType value) {
        this.resourceRequestID = value;
    }

    public boolean isSetResourceRequestID() {
        return (this.resourceRequestID!= null);
    }

    /**
     * Gets the value of the naturalResourceRequestKey property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRequestNaturalKeyType }
     *     
     */
    public ResourceRequestNaturalKeyType getNaturalResourceRequestKey() {
        return naturalResourceRequestKey;
    }

    /**
     * Sets the value of the naturalResourceRequestKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRequestNaturalKeyType }
     *     
     */
    public void setNaturalResourceRequestKey(ResourceRequestNaturalKeyType value) {
        this.naturalResourceRequestKey = value;
    }

    public boolean isSetNaturalResourceRequestKey() {
        return (this.naturalResourceRequestKey!= null);
    }

}
