//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing Key information referring to a specific incident Aviation Hazard across the ROSS Services Interface.
 * 
 * <p>Java class for CompositeIncidentAviationHazardKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompositeIncidentAviationHazardKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncidentAviationHazardID" type="{http://nwcg.gov/services/ross/common_types/1.1}IDType"/>
 *         &lt;element name="IncidentAviationHazardNaturalKey" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentAviationHazardNaturalKeyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompositeIncidentAviationHazardKeyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "incidentAviationHazardID",
    "incidentAviationHazardNaturalKey"
})
public class CompositeIncidentAviationHazardKeyType {

    @XmlElement(name = "IncidentAviationHazardID", required = true)
    protected IDType incidentAviationHazardID;
    @XmlElement(name = "IncidentAviationHazardNaturalKey", required = true)
    protected IncidentAviationHazardNaturalKeyType incidentAviationHazardNaturalKey;

    /**
     * Gets the value of the incidentAviationHazardID property.
     * 
     * @return
     *     possible object is
     *     {@link IDType }
     *     
     */
    public IDType getIncidentAviationHazardID() {
        return incidentAviationHazardID;
    }

    /**
     * Sets the value of the incidentAviationHazardID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDType }
     *     
     */
    public void setIncidentAviationHazardID(IDType value) {
        this.incidentAviationHazardID = value;
    }

    public boolean isSetIncidentAviationHazardID() {
        return (this.incidentAviationHazardID!= null);
    }

    /**
     * Gets the value of the incidentAviationHazardNaturalKey property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentAviationHazardNaturalKeyType }
     *     
     */
    public IncidentAviationHazardNaturalKeyType getIncidentAviationHazardNaturalKey() {
        return incidentAviationHazardNaturalKey;
    }

    /**
     * Sets the value of the incidentAviationHazardNaturalKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentAviationHazardNaturalKeyType }
     *     
     */
    public void setIncidentAviationHazardNaturalKey(IncidentAviationHazardNaturalKeyType value) {
        this.incidentAviationHazardNaturalKey = value;
    }

    public boolean isSetIncidentAviationHazardNaturalKey() {
        return (this.incidentAviationHazardNaturalKey!= null);
    }

}
