//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing the external system to notify
 * 
 * <p>Java class for ExternalSystemToNotifyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExternalSystemToNotifyType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nwcg.gov/services/ross/common_types/1.1}ApplicationSystemType">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExternalSystemToNotifyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1")
public class ExternalSystemToNotifyType
    extends ApplicationSystemType
{


}
