//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Structure containing Incident attributes used during creation
 * 
 * <p>Java class for IncidentDetailsCreateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentDetailsCreateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncidentName" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentNameSimpleType" minOccurs="0"/>
 *         &lt;element name="IncidentType" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentTypeSimpleType"/>
 *         &lt;element name="InitialDatetime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="IncidentLocation" type="{http://nwcg.gov/services/ross/common_types/1.1}LocationCreateType"/>
 *         &lt;element name="LocationName" type="{http://nwcg.gov/services/ross/common_types/1.1}LocationNameSimpleType" minOccurs="0"/>
 *         &lt;element name="IsComplexIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="OfficeReferenceNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}OfficeReferenceNumberSimpleType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentDescriptionSimpleType" minOccurs="0"/>
 *         &lt;element name="OriginatingSystemUserData" type="{http://nwcg.gov/services/ross/common_types/1.1}OriginatingSystemUserDataSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentDetailsCreateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "incidentName",
    "incidentType",
    "initialDatetime",
    "incidentLocation",
    "locationName",
    "isComplexIndicator",
    "officeReferenceNumber",
    "description",
    "originatingSystemUserData"
})
public class IncidentDetailsCreateType {

    @XmlElement(name = "IncidentName")
    protected String incidentName;
    @XmlElement(name = "IncidentType", required = true, defaultValue = "FireWildfire")
    protected String incidentType;
    @XmlElement(name = "InitialDatetime", required = true)
    protected XMLGregorianCalendar initialDatetime;
    @XmlElement(name = "IncidentLocation", required = true)
    protected LocationCreateType incidentLocation;
    @XmlElement(name = "LocationName")
    protected String locationName;
    @XmlElement(name = "IsComplexIndicator", defaultValue = "false")
    protected Boolean isComplexIndicator;
    @XmlElement(name = "OfficeReferenceNumber")
    protected String officeReferenceNumber;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "OriginatingSystemUserData")
    protected String originatingSystemUserData;

    /**
     * Gets the value of the incidentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentName() {
        return incidentName;
    }

    /**
     * Sets the value of the incidentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentName(String value) {
        this.incidentName = value;
    }

    public boolean isSetIncidentName() {
        return (this.incidentName!= null);
    }

    /**
     * Gets the value of the incidentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentType() {
        return incidentType;
    }

    /**
     * Sets the value of the incidentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentType(String value) {
        this.incidentType = value;
    }

    public boolean isSetIncidentType() {
        return (this.incidentType!= null);
    }

    /**
     * Gets the value of the initialDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInitialDatetime() {
        return initialDatetime;
    }

    /**
     * Sets the value of the initialDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInitialDatetime(XMLGregorianCalendar value) {
        this.initialDatetime = value;
    }

    public boolean isSetInitialDatetime() {
        return (this.initialDatetime!= null);
    }

    /**
     * Gets the value of the incidentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationCreateType }
     *     
     */
    public LocationCreateType getIncidentLocation() {
        return incidentLocation;
    }

    /**
     * Sets the value of the incidentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationCreateType }
     *     
     */
    public void setIncidentLocation(LocationCreateType value) {
        this.incidentLocation = value;
    }

    public boolean isSetIncidentLocation() {
        return (this.incidentLocation!= null);
    }

    /**
     * Gets the value of the locationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * Sets the value of the locationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationName(String value) {
        this.locationName = value;
    }

    public boolean isSetLocationName() {
        return (this.locationName!= null);
    }

    /**
     * Gets the value of the isComplexIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsComplexIndicator() {
        return isComplexIndicator;
    }

    /**
     * Sets the value of the isComplexIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsComplexIndicator(Boolean value) {
        this.isComplexIndicator = value;
    }

    public boolean isSetIsComplexIndicator() {
        return (this.isComplexIndicator!= null);
    }

    /**
     * Gets the value of the officeReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficeReferenceNumber() {
        return officeReferenceNumber;
    }

    /**
     * Sets the value of the officeReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficeReferenceNumber(String value) {
        this.officeReferenceNumber = value;
    }

    public boolean isSetOfficeReferenceNumber() {
        return (this.officeReferenceNumber!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

    /**
     * Gets the value of the originatingSystemUserData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingSystemUserData() {
        return originatingSystemUserData;
    }

    /**
     * Sets the value of the originatingSystemUserData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingSystemUserData(String value) {
        this.originatingSystemUserData = value;
    }

    public boolean isSetOriginatingSystemUserData() {
        return (this.originatingSystemUserData!= null);
    }

}
