//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing Incident related entities such as Radio Frequency provided to external systems
 * 
 * <p>Java class for IncidentEntitiesReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentEntitiesReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncidentRadioFrequencies" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentRadioFrequencyReturnType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Documentation" type="{http://nwcg.gov/services/ross/common_types/1.1}DocumentationReturnType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentAviationHazards" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentAviationHazardReturnType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentAddresses" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentAddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentRequestBlocks" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentRequestBlockType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentFinancialCodes" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentFinancialCodeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IncidentContacts" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentContactType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentEntitiesReturnType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "incidentRadioFrequencies",
    "documentation",
    "incidentAviationHazards",
    "incidentAddresses",
    "incidentRequestBlocks",
    "incidentFinancialCodes",
    "incidentContacts"
})
public class IncidentEntitiesReturnType {

    @XmlElement(name = "IncidentRadioFrequencies")
    protected List<IncidentRadioFrequencyReturnType> incidentRadioFrequencies;
    @XmlElement(name = "Documentation")
    protected List<DocumentationReturnType> documentation;
    @XmlElement(name = "IncidentAviationHazards")
    protected List<IncidentAviationHazardReturnType> incidentAviationHazards;
    @XmlElement(name = "IncidentAddresses")
    protected List<IncidentAddressType> incidentAddresses;
    @XmlElement(name = "IncidentRequestBlocks")
    protected List<IncidentRequestBlockType> incidentRequestBlocks;
    @XmlElement(name = "IncidentFinancialCodes")
    protected List<IncidentFinancialCodeType> incidentFinancialCodes;
    @XmlElement(name = "IncidentContacts")
    protected List<IncidentContactType> incidentContacts;

    /**
     * Gets the value of the incidentRadioFrequencies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentRadioFrequencies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentRadioFrequencies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentRadioFrequencyReturnType }
     * 
     * 
     */
    public List<IncidentRadioFrequencyReturnType> getIncidentRadioFrequencies() {
        if (incidentRadioFrequencies == null) {
            incidentRadioFrequencies = new ArrayList<IncidentRadioFrequencyReturnType>();
        }
        return this.incidentRadioFrequencies;
    }

    public boolean isSetIncidentRadioFrequencies() {
        return ((this.incidentRadioFrequencies!= null)&&(!this.incidentRadioFrequencies.isEmpty()));
    }

    public void unsetIncidentRadioFrequencies() {
        this.incidentRadioFrequencies = null;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the documentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocumentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentationReturnType }
     * 
     * 
     */
    public List<DocumentationReturnType> getDocumentation() {
        if (documentation == null) {
            documentation = new ArrayList<DocumentationReturnType>();
        }
        return this.documentation;
    }

    public boolean isSetDocumentation() {
        return ((this.documentation!= null)&&(!this.documentation.isEmpty()));
    }

    public void unsetDocumentation() {
        this.documentation = null;
    }

    /**
     * Gets the value of the incidentAviationHazards property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentAviationHazards property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentAviationHazards().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentAviationHazardReturnType }
     * 
     * 
     */
    public List<IncidentAviationHazardReturnType> getIncidentAviationHazards() {
        if (incidentAviationHazards == null) {
            incidentAviationHazards = new ArrayList<IncidentAviationHazardReturnType>();
        }
        return this.incidentAviationHazards;
    }

    public boolean isSetIncidentAviationHazards() {
        return ((this.incidentAviationHazards!= null)&&(!this.incidentAviationHazards.isEmpty()));
    }

    public void unsetIncidentAviationHazards() {
        this.incidentAviationHazards = null;
    }

    /**
     * Gets the value of the incidentAddresses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentAddresses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentAddresses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentAddressType }
     * 
     * 
     */
    public List<IncidentAddressType> getIncidentAddresses() {
        if (incidentAddresses == null) {
            incidentAddresses = new ArrayList<IncidentAddressType>();
        }
        return this.incidentAddresses;
    }

    public boolean isSetIncidentAddresses() {
        return ((this.incidentAddresses!= null)&&(!this.incidentAddresses.isEmpty()));
    }

    public void unsetIncidentAddresses() {
        this.incidentAddresses = null;
    }

    /**
     * Gets the value of the incidentRequestBlocks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentRequestBlocks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentRequestBlocks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentRequestBlockType }
     * 
     * 
     */
    public List<IncidentRequestBlockType> getIncidentRequestBlocks() {
        if (incidentRequestBlocks == null) {
            incidentRequestBlocks = new ArrayList<IncidentRequestBlockType>();
        }
        return this.incidentRequestBlocks;
    }

    public boolean isSetIncidentRequestBlocks() {
        return ((this.incidentRequestBlocks!= null)&&(!this.incidentRequestBlocks.isEmpty()));
    }

    public void unsetIncidentRequestBlocks() {
        this.incidentRequestBlocks = null;
    }

    /**
     * Gets the value of the incidentFinancialCodes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentFinancialCodes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentFinancialCodes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentFinancialCodeType }
     * 
     * 
     */
    public List<IncidentFinancialCodeType> getIncidentFinancialCodes() {
        if (incidentFinancialCodes == null) {
            incidentFinancialCodes = new ArrayList<IncidentFinancialCodeType>();
        }
        return this.incidentFinancialCodes;
    }

    public boolean isSetIncidentFinancialCodes() {
        return ((this.incidentFinancialCodes!= null)&&(!this.incidentFinancialCodes.isEmpty()));
    }

    public void unsetIncidentFinancialCodes() {
        this.incidentFinancialCodes = null;
    }

    /**
     * Gets the value of the incidentContacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incidentContacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncidentContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncidentContactType }
     * 
     * 
     */
    public List<IncidentContactType> getIncidentContacts() {
        if (incidentContacts == null) {
            incidentContacts = new ArrayList<IncidentContactType>();
        }
        return this.incidentContacts;
    }

    public boolean isSetIncidentContacts() {
        return ((this.incidentContacts!= null)&&(!this.incidentContacts.isEmpty()));
    }

    public void unsetIncidentContacts() {
        this.incidentContacts = null;
    }

}
