//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Structure containing Incident Attributes to be modified
 * 
 * <p>Java class for IncidentDetailsUpdateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentDetailsUpdateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncidentName" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentNameSimpleType" minOccurs="0"/>
 *         &lt;element name="IncidentType" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentTypeSimpleType" minOccurs="0"/>
 *         &lt;element name="InitialDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LocationName" type="{http://nwcg.gov/services/ross/common_types/1.1}LocationNameSimpleType" minOccurs="0"/>
 *         &lt;element name="IncidentLocation" type="{http://nwcg.gov/services/ross/common_types/1.1}LocationCreateType" minOccurs="0"/>
 *         &lt;element name="OfficeReferenceNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}OfficeReferenceNumberSimpleType" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentDescriptionSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentDetailsUpdateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "incidentName",
    "incidentType",
    "initialDateTime",
    "locationName",
    "incidentLocation",
    "officeReferenceNumber",
    "description"
})
public class IncidentDetailsUpdateType {

    @XmlElement(name = "IncidentName")
    protected String incidentName;
    @XmlElement(name = "IncidentType")
    protected String incidentType;
    @XmlElement(name = "InitialDateTime")
    protected XMLGregorianCalendar initialDateTime;
    @XmlElement(name = "LocationName")
    protected String locationName;
    @XmlElement(name = "IncidentLocation")
    protected LocationCreateType incidentLocation;
    @XmlElement(name = "OfficeReferenceNumber")
    protected String officeReferenceNumber;
    @XmlElement(name = "Description")
    protected String description;

    /**
     * Gets the value of the incidentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentName() {
        return incidentName;
    }

    /**
     * Sets the value of the incidentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentName(String value) {
        this.incidentName = value;
    }

    public boolean isSetIncidentName() {
        return (this.incidentName!= null);
    }

    /**
     * Gets the value of the incidentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentType() {
        return incidentType;
    }

    /**
     * Sets the value of the incidentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentType(String value) {
        this.incidentType = value;
    }

    public boolean isSetIncidentType() {
        return (this.incidentType!= null);
    }

    /**
     * Gets the value of the initialDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInitialDateTime() {
        return initialDateTime;
    }

    /**
     * Sets the value of the initialDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInitialDateTime(XMLGregorianCalendar value) {
        this.initialDateTime = value;
    }

    public boolean isSetInitialDateTime() {
        return (this.initialDateTime!= null);
    }

    /**
     * Gets the value of the locationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * Sets the value of the locationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationName(String value) {
        this.locationName = value;
    }

    public boolean isSetLocationName() {
        return (this.locationName!= null);
    }

    /**
     * Gets the value of the incidentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationCreateType }
     *     
     */
    public LocationCreateType getIncidentLocation() {
        return incidentLocation;
    }

    /**
     * Sets the value of the incidentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationCreateType }
     *     
     */
    public void setIncidentLocation(LocationCreateType value) {
        this.incidentLocation = value;
    }

    public boolean isSetIncidentLocation() {
        return (this.incidentLocation!= null);
    }

    /**
     * Gets the value of the officeReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficeReferenceNumber() {
        return officeReferenceNumber;
    }

    /**
     * Sets the value of the officeReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficeReferenceNumber(String value) {
        this.officeReferenceNumber = value;
    }

    public boolean isSetOfficeReferenceNumber() {
        return (this.officeReferenceNumber!= null);
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    public boolean isSetDescription() {
        return (this.description!= null);
    }

}
