//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing Incident Attributes that comprise the Incident Number
 * 
 * <p>Java class for IncidentNumberType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentNumberType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HostID" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType"/>
 *         &lt;element name="SequenceNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentSequenceNumberSimpleType"/>
 *         &lt;element name="YearCreated">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *               &lt;pattern value="20[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentNumberType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "hostID",
    "sequenceNumber",
    "yearCreated"
})
public class IncidentNumberType {

    @XmlElement(name = "HostID", required = true)
    protected UnitIDType hostID;
    @XmlElement(name = "SequenceNumber")
    protected int sequenceNumber;
    @XmlElement(name = "YearCreated", required = true)
    protected String yearCreated;

    /**
     * Gets the value of the hostID property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getHostID() {
        return hostID;
    }

    /**
     * Sets the value of the hostID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setHostID(UnitIDType value) {
        this.hostID = value;
    }

    public boolean isSetHostID() {
        return (this.hostID!= null);
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     */
    public int getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     */
    public void setSequenceNumber(int value) {
        this.sequenceNumber = value;
    }

    public boolean isSetSequenceNumber() {
        return true;
    }

    /**
     * Gets the value of the yearCreated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearCreated() {
        return yearCreated;
    }

    /**
     * Sets the value of the yearCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearCreated(String value) {
        this.yearCreated = value;
    }

    public boolean isSetYearCreated() {
        return (this.yearCreated!= null);
    }

}
