//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing contact info for an incident
 * 
 * <p>Java class for IncidentContactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentContactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://nwcg.gov/services/ross/common_types/1.1}IncidentContactTypeSimpleType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://nwcg.gov/services/ross/common_types/1.1}ShippingContactNameSimpleType" minOccurs="0"/>
 *         &lt;element name="Information" type="{http://nwcg.gov/services/ross/common_types/1.1}ShippingContactPhoneSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentContactType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "type",
    "name",
    "information"
})
public class IncidentContactType {

    @XmlElement(name = "Type")
    protected IncidentContactTypeSimpleType type;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Information")
    protected String information;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link IncidentContactTypeSimpleType }
     *     
     */
    public IncidentContactTypeSimpleType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncidentContactTypeSimpleType }
     *     
     */
    public void setType(IncidentContactTypeSimpleType value) {
        this.type = value;
    }

    public boolean isSetType() {
        return (this.type!= null);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public boolean isSetName() {
        return (this.name!= null);
    }

    /**
     * Gets the value of the information property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformation() {
        return information;
    }

    /**
     * Sets the value of the information property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformation(String value) {
        this.information = value;
    }

    public boolean isSetInformation() {
        return (this.information!= null);
    }

}
