//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Person (overhead) resource data
 * 
 * <p>Java class for PersonResourceCreateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonResourceCreateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProviderUnitID" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType"/>
 *         &lt;element name="EmploymentClass" type="{http://nwcg.gov/services/ross/common_types/1.1}EmploymentClassSimpleType"/>
 *         &lt;element name="AgencyCode" type="{http://nwcg.gov/services/ross/common_types/1.1}AgencyCodeSimpleType" minOccurs="0"/>
 *         &lt;element name="Contacts" type="{http://nwcg.gov/services/ross/common_types/1.1}PersonOrOrganizationContact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PreferredJetport" type="{http://nwcg.gov/services/ross/common_types/1.1}AirportNaturalKeyType" minOccurs="0"/>
 *         &lt;element name="BodyWeight" type="{http://nwcg.gov/services/ross/common_types/1.1}BodyWeightSimpleType" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://nwcg.gov/services/ross/common_types/1.1}GenderSimpleType" minOccurs="0"/>
 *         &lt;element name="Qualifications" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceQualificationType" maxOccurs="unbounded"/>
 *         &lt;element name="Fitness" type="{http://nwcg.gov/services/ross/common_types/1.1}PersonResourceFitnessType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonResourceCreateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "providerUnitID",
    "employmentClass",
    "agencyCode",
    "contacts",
    "preferredJetport",
    "bodyWeight",
    "gender",
    "qualifications",
    "fitness"
})
public class PersonResourceCreateType {

    @XmlElement(name = "ProviderUnitID", required = true)
    protected UnitIDType providerUnitID;
    @XmlElement(name = "EmploymentClass", required = true)
    protected String employmentClass;
    @XmlElement(name = "AgencyCode")
    protected String agencyCode;
    @XmlElement(name = "Contacts")
    protected List<PersonOrOrganizationContact> contacts;
    @XmlElement(name = "PreferredJetport")
    protected AirportNaturalKeyType preferredJetport;
    @XmlElement(name = "BodyWeight")
    protected Integer bodyWeight;
    @XmlElement(name = "Gender")
    protected GenderSimpleType gender;
    @XmlElement(name = "Qualifications", required = true)
    protected List<ResourceQualificationType> qualifications;
    @XmlElement(name = "Fitness")
    protected PersonResourceFitnessType fitness;

    /**
     * Gets the value of the providerUnitID property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getProviderUnitID() {
        return providerUnitID;
    }

    /**
     * Sets the value of the providerUnitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setProviderUnitID(UnitIDType value) {
        this.providerUnitID = value;
    }

    public boolean isSetProviderUnitID() {
        return (this.providerUnitID!= null);
    }

    /**
     * Gets the value of the employmentClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmploymentClass() {
        return employmentClass;
    }

    /**
     * Sets the value of the employmentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmploymentClass(String value) {
        this.employmentClass = value;
    }

    public boolean isSetEmploymentClass() {
        return (this.employmentClass!= null);
    }

    /**
     * Gets the value of the agencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgencyCode() {
        return agencyCode;
    }

    /**
     * Sets the value of the agencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgencyCode(String value) {
        this.agencyCode = value;
    }

    public boolean isSetAgencyCode() {
        return (this.agencyCode!= null);
    }

    /**
     * Gets the value of the contacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonOrOrganizationContact }
     * 
     * 
     */
    public List<PersonOrOrganizationContact> getContacts() {
        if (contacts == null) {
            contacts = new ArrayList<PersonOrOrganizationContact>();
        }
        return this.contacts;
    }

    public boolean isSetContacts() {
        return ((this.contacts!= null)&&(!this.contacts.isEmpty()));
    }

    public void unsetContacts() {
        this.contacts = null;
    }

    /**
     * Gets the value of the preferredJetport property.
     * 
     * @return
     *     possible object is
     *     {@link AirportNaturalKeyType }
     *     
     */
    public AirportNaturalKeyType getPreferredJetport() {
        return preferredJetport;
    }

    /**
     * Sets the value of the preferredJetport property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirportNaturalKeyType }
     *     
     */
    public void setPreferredJetport(AirportNaturalKeyType value) {
        this.preferredJetport = value;
    }

    public boolean isSetPreferredJetport() {
        return (this.preferredJetport!= null);
    }

    /**
     * Gets the value of the bodyWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBodyWeight() {
        return bodyWeight;
    }

    /**
     * Sets the value of the bodyWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBodyWeight(Integer value) {
        this.bodyWeight = value;
    }

    public boolean isSetBodyWeight() {
        return (this.bodyWeight!= null);
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderSimpleType }
     *     
     */
    public GenderSimpleType getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderSimpleType }
     *     
     */
    public void setGender(GenderSimpleType value) {
        this.gender = value;
    }

    public boolean isSetGender() {
        return (this.gender!= null);
    }

    /**
     * Gets the value of the qualifications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the qualifications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQualifications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceQualificationType }
     * 
     * 
     */
    public List<ResourceQualificationType> getQualifications() {
        if (qualifications == null) {
            qualifications = new ArrayList<ResourceQualificationType>();
        }
        return this.qualifications;
    }

    public boolean isSetQualifications() {
        return ((this.qualifications!= null)&&(!this.qualifications.isEmpty()));
    }

    public void unsetQualifications() {
        this.qualifications = null;
    }

    /**
     * Gets the value of the fitness property.
     * 
     * @return
     *     possible object is
     *     {@link PersonResourceFitnessType }
     *     
     */
    public PersonResourceFitnessType getFitness() {
        return fitness;
    }

    /**
     * Sets the value of the fitness property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonResourceFitnessType }
     *     
     */
    public void setFitness(PersonResourceFitnessType value) {
        this.fitness = value;
    }

    public boolean isSetFitness() {
        return (this.fitness!= null);
    }

}
