//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Unique identifier for a person, such as Social Security Number
 * 
 * <p>Java class for PersonalIdentificationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalIdentificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IdentificationType" type="{http://nwcg.gov/services/ross/common_types/1.1}PersonalIdentificationTypeSimpleType"/>
 *         &lt;element name="Identification" type="{http://nwcg.gov/services/ross/common_types/1.1}PersonalIdentificationSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalIdentificationType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "identificationType",
    "identification"
})
public class PersonalIdentificationType {

    @XmlElement(name = "IdentificationType", required = true)
    protected PersonalIdentificationTypeSimpleType identificationType;
    @XmlElement(name = "Identification", required = true)
    protected String identification;

    /**
     * Gets the value of the identificationType property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalIdentificationTypeSimpleType }
     *     
     */
    public PersonalIdentificationTypeSimpleType getIdentificationType() {
        return identificationType;
    }

    /**
     * Sets the value of the identificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalIdentificationTypeSimpleType }
     *     
     */
    public void setIdentificationType(PersonalIdentificationTypeSimpleType value) {
        this.identificationType = value;
    }

    public boolean isSetIdentificationType() {
        return (this.identificationType!= null);
    }

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentification(String value) {
        this.identification = value;
    }

    public boolean isSetIdentification() {
        return (this.identification!= null);
    }

}
