//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing the Resource Request Code -ex A-1
 * 
 * <p>Java class for RequestCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequestCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogID" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogID"/>
 *         &lt;element name="SequenceNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogSequenceNumber"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequestCodeType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "catalogID",
    "sequenceNumber"
})
public class RequestCodeType {

    @XmlElement(name = "CatalogID", required = true)
    protected CatalogID catalogID;
    @XmlElement(name = "SequenceNumber", required = true)
    protected String sequenceNumber;

    /**
     * Gets the value of the catalogID property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogID }
     *     
     */
    public CatalogID getCatalogID() {
        return catalogID;
    }

    /**
     * Sets the value of the catalogID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogID }
     *     
     */
    public void setCatalogID(CatalogID value) {
        this.catalogID = value;
    }

    public boolean isSetCatalogID() {
        return (this.catalogID!= null);
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    public boolean isSetSequenceNumber() {
        return (this.sequenceNumber!= null);
    }

}
