//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestInclusionSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestInclusionSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None"/>
 *     &lt;enumeration value="FederalOnly"/>
 *     &lt;enumeration value="HostAgencyOnly"/>
 *     &lt;enumeration value="StateOnly"/>
 *     &lt;enumeration value="NonFederalOnly"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
@XmlType(name = "RequestInclusionSimpleType", namespace = "http://nwcg.gov/services/ross/common_types/1.1")
public enum RequestInclusionSimpleType {

    @XmlEnumValue("None")
    NONE("None"),
    @XmlEnumValue("FederalOnly")
    FEDERAL_ONLY("FederalOnly"),
    @XmlEnumValue("HostAgencyOnly")
    HOST_AGENCY_ONLY("HostAgencyOnly"),
    @XmlEnumValue("StateOnly")
    STATE_ONLY("StateOnly"),
    @XmlEnumValue("NonFederalOnly")
    NON_FEDERAL_ONLY("NonFederalOnly");
    private final String value;

    RequestInclusionSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestInclusionSimpleType fromValue(String v) {
        for (RequestInclusionSimpleType c: RequestInclusionSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
