//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Structure containing information needed to perform a fill
 * 
 * <p>Java class for ResourceRequestFillOperationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceRequestFillOperationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeResourceKeyType"/>
 *         &lt;element name="MobilizationETD" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MobilizationETA" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="FillType" type="{http://nwcg.gov/services/ross/common_types/1.1}FillOperationTypeSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceRequestFillOperationType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "resourceKey",
    "mobilizationETD",
    "mobilizationETA",
    "fillType"
})
public class ResourceRequestFillOperationType {

    @XmlElement(name = "ResourceKey", required = true)
    protected CompositeResourceKeyType resourceKey;
    @XmlElement(name = "MobilizationETD", required = true)
    protected XMLGregorianCalendar mobilizationETD;
    @XmlElement(name = "MobilizationETA", required = true)
    protected XMLGregorianCalendar mobilizationETA;
    @XmlElement(name = "FillType", required = true)
    protected FillOperationTypeSimpleType fillType;

    /**
     * Gets the value of the resourceKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeResourceKeyType }
     *     
     */
    public CompositeResourceKeyType getResourceKey() {
        return resourceKey;
    }

    /**
     * Sets the value of the resourceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeResourceKeyType }
     *     
     */
    public void setResourceKey(CompositeResourceKeyType value) {
        this.resourceKey = value;
    }

    public boolean isSetResourceKey() {
        return (this.resourceKey!= null);
    }

    /**
     * Gets the value of the mobilizationETD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMobilizationETD() {
        return mobilizationETD;
    }

    /**
     * Sets the value of the mobilizationETD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMobilizationETD(XMLGregorianCalendar value) {
        this.mobilizationETD = value;
    }

    public boolean isSetMobilizationETD() {
        return (this.mobilizationETD!= null);
    }

    /**
     * Gets the value of the mobilizationETA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMobilizationETA() {
        return mobilizationETA;
    }

    /**
     * Sets the value of the mobilizationETA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMobilizationETA(XMLGregorianCalendar value) {
        this.mobilizationETA = value;
    }

    public boolean isSetMobilizationETA() {
        return (this.mobilizationETA!= null);
    }

    /**
     * Gets the value of the fillType property.
     * 
     * @return
     *     possible object is
     *     {@link FillOperationTypeSimpleType }
     *     
     */
    public FillOperationTypeSimpleType getFillType() {
        return fillType;
    }

    /**
     * Sets the value of the fillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillOperationTypeSimpleType }
     *     
     */
    public void setFillType(FillOperationTypeSimpleType value) {
        this.fillType = value;
    }

    public boolean isSetFillType() {
        return (this.fillType!= null);
    }

}
