//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Resource qualification data (for update)
 * 
 * <p>Java class for ResourceQualificationUpdateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceQualificationUpdateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogItem" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemType"/>
 *         &lt;element name="QualificationStatus" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceQualificationStatusSimpleType" minOccurs="0"/>
 *         &lt;element name="QualificationExpirationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceQualificationUpdateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "catalogItem",
    "qualificationStatus",
    "qualificationExpirationDate"
})
public class ResourceQualificationUpdateType {

    @XmlElement(name = "CatalogItem", required = true)
    protected CatalogItemType catalogItem;
    @XmlElement(name = "QualificationStatus")
    protected ResourceQualificationStatusSimpleType qualificationStatus;
    @XmlElement(name = "QualificationExpirationDate")
    protected XMLGregorianCalendar qualificationExpirationDate;

    /**
     * Gets the value of the catalogItem property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogItemType }
     *     
     */
    public CatalogItemType getCatalogItem() {
        return catalogItem;
    }

    /**
     * Sets the value of the catalogItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogItemType }
     *     
     */
    public void setCatalogItem(CatalogItemType value) {
        this.catalogItem = value;
    }

    public boolean isSetCatalogItem() {
        return (this.catalogItem!= null);
    }

    /**
     * Gets the value of the qualificationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceQualificationStatusSimpleType }
     *     
     */
    public ResourceQualificationStatusSimpleType getQualificationStatus() {
        return qualificationStatus;
    }

    /**
     * Sets the value of the qualificationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceQualificationStatusSimpleType }
     *     
     */
    public void setQualificationStatus(ResourceQualificationStatusSimpleType value) {
        this.qualificationStatus = value;
    }

    public boolean isSetQualificationStatus() {
        return (this.qualificationStatus!= null);
    }

    /**
     * Gets the value of the qualificationExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getQualificationExpirationDate() {
        return qualificationExpirationDate;
    }

    /**
     * Sets the value of the qualificationExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setQualificationExpirationDate(XMLGregorianCalendar value) {
        this.qualificationExpirationDate = value;
    }

    public boolean isSetQualificationExpirationDate() {
        return (this.qualificationExpirationDate!= null);
    }

}
