//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Structure containing base resource request information returned to external systems
 * 
 * <p>Java class for ResourceRequestBaseReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceRequestBaseReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="NeedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="RequestedItemName" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemDescriptionSimpleType"/>
 *         &lt;element name="InclusionType" type="{http://nwcg.gov/services/ross/common_types/1.1}RequestInclusionSimpleType"/>
 *         &lt;element name="SystemOfOrigin" type="{http://nwcg.gov/services/ross/common_types/1.1}ApplicationSystemType"/>
 *         &lt;element name="Restrictions" type="{http://nwcg.gov/services/ross/common_types/1.1}RequestRestrictionSimpleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SpecialNeeds" type="{http://nwcg.gov/services/ross/common_types/1.1}SpecialNeedsSimpleType" minOccurs="0"/>
 *         &lt;element name="NamedRequestIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CallSignRequiredIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="QuantityRequested" type="{http://nwcg.gov/services/ross/common_types/1.1}QuantitySimpleType"/>
 *         &lt;element name="RequestingContact" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestContactReturnType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceRequestBaseReturnType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "orderDateTime",
    "needDateTime",
    "requestedItemName",
    "inclusionType",
    "systemOfOrigin",
    "restrictions",
    "specialNeeds",
    "namedRequestIndicator",
    "callSignRequiredIndicator",
    "quantityRequested",
    "requestingContact"
})
public class ResourceRequestBaseReturnType {

    @XmlElement(name = "OrderDateTime", required = true)
    protected XMLGregorianCalendar orderDateTime;
    @XmlElement(name = "NeedDateTime", required = true)
    protected XMLGregorianCalendar needDateTime;
    @XmlElement(name = "RequestedItemName", required = true)
    protected String requestedItemName;
    @XmlElement(name = "InclusionType", required = true)
    protected RequestInclusionSimpleType inclusionType;
    @XmlElement(name = "SystemOfOrigin", required = true)
    protected ApplicationSystemType systemOfOrigin;
    @XmlElement(name = "Restrictions")
    protected List<RequestRestrictionSimpleType> restrictions;
    @XmlElement(name = "SpecialNeeds")
    protected String specialNeeds;
    @XmlElement(name = "NamedRequestIndicator")
    protected boolean namedRequestIndicator;
    @XmlElement(name = "CallSignRequiredIndicator")
    protected boolean callSignRequiredIndicator;
    @XmlElement(name = "QuantityRequested")
    protected int quantityRequested;
    @XmlElement(name = "RequestingContact", required = true)
    protected ResourceRequestContactReturnType requestingContact;

    /**
     * Gets the value of the orderDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderDateTime() {
        return orderDateTime;
    }

    /**
     * Sets the value of the orderDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderDateTime(XMLGregorianCalendar value) {
        this.orderDateTime = value;
    }

    public boolean isSetOrderDateTime() {
        return (this.orderDateTime!= null);
    }

    /**
     * Gets the value of the needDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNeedDateTime() {
        return needDateTime;
    }

    /**
     * Sets the value of the needDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNeedDateTime(XMLGregorianCalendar value) {
        this.needDateTime = value;
    }

    public boolean isSetNeedDateTime() {
        return (this.needDateTime!= null);
    }

    /**
     * Gets the value of the requestedItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedItemName() {
        return requestedItemName;
    }

    /**
     * Sets the value of the requestedItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedItemName(String value) {
        this.requestedItemName = value;
    }

    public boolean isSetRequestedItemName() {
        return (this.requestedItemName!= null);
    }

    /**
     * Gets the value of the inclusionType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestInclusionSimpleType }
     *     
     */
    public RequestInclusionSimpleType getInclusionType() {
        return inclusionType;
    }

    /**
     * Sets the value of the inclusionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestInclusionSimpleType }
     *     
     */
    public void setInclusionType(RequestInclusionSimpleType value) {
        this.inclusionType = value;
    }

    public boolean isSetInclusionType() {
        return (this.inclusionType!= null);
    }

    /**
     * Gets the value of the systemOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationSystemType }
     *     
     */
    public ApplicationSystemType getSystemOfOrigin() {
        return systemOfOrigin;
    }

    /**
     * Sets the value of the systemOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationSystemType }
     *     
     */
    public void setSystemOfOrigin(ApplicationSystemType value) {
        this.systemOfOrigin = value;
    }

    public boolean isSetSystemOfOrigin() {
        return (this.systemOfOrigin!= null);
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestRestrictionSimpleType }
     * 
     * 
     */
    public List<RequestRestrictionSimpleType> getRestrictions() {
        if (restrictions == null) {
            restrictions = new ArrayList<RequestRestrictionSimpleType>();
        }
        return this.restrictions;
    }

    public boolean isSetRestrictions() {
        return ((this.restrictions!= null)&&(!this.restrictions.isEmpty()));
    }

    public void unsetRestrictions() {
        this.restrictions = null;
    }

    /**
     * Gets the value of the specialNeeds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialNeeds() {
        return specialNeeds;
    }

    /**
     * Sets the value of the specialNeeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialNeeds(String value) {
        this.specialNeeds = value;
    }

    public boolean isSetSpecialNeeds() {
        return (this.specialNeeds!= null);
    }

    /**
     * Gets the value of the namedRequestIndicator property.
     * 
     */
    public boolean isNamedRequestIndicator() {
        return namedRequestIndicator;
    }

    /**
     * Sets the value of the namedRequestIndicator property.
     * 
     */
    public void setNamedRequestIndicator(boolean value) {
        this.namedRequestIndicator = value;
    }

    public boolean isSetNamedRequestIndicator() {
        return true;
    }

    /**
     * Gets the value of the callSignRequiredIndicator property.
     * 
     */
    public boolean isCallSignRequiredIndicator() {
        return callSignRequiredIndicator;
    }

    /**
     * Sets the value of the callSignRequiredIndicator property.
     * 
     */
    public void setCallSignRequiredIndicator(boolean value) {
        this.callSignRequiredIndicator = value;
    }

    public boolean isSetCallSignRequiredIndicator() {
        return true;
    }

    /**
     * Gets the value of the quantityRequested property.
     * 
     */
    public int getQuantityRequested() {
        return quantityRequested;
    }

    /**
     * Sets the value of the quantityRequested property.
     * 
     */
    public void setQuantityRequested(int value) {
        this.quantityRequested = value;
    }

    public boolean isSetQuantityRequested() {
        return true;
    }

    /**
     * Gets the value of the requestingContact property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRequestContactReturnType }
     *     
     */
    public ResourceRequestContactReturnType getRequestingContact() {
        return requestingContact;
    }

    /**
     * Sets the value of the requestingContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRequestContactReturnType }
     *     
     */
    public void setRequestingContact(ResourceRequestContactReturnType value) {
        this.requestingContact = value;
    }

    public boolean isSetRequestingContact() {
        return (this.requestingContact!= null);
    }

}
