//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details on kit items filled by ICBS
 * 
 * <p>Java class for SubordinateDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubordinateDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubordinateRequest" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubordinateRequestNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}RequestCodeType"/>
 *                   &lt;element name="FilledItem" type="{http://nwcg.gov/services/ross/common_types/1.1}FillDetailType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubordinateDetailType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "subordinateRequest"
})
public class SubordinateDetailType {

    @XmlElement(name = "SubordinateRequest", required = true)
    protected List<SubordinateDetailType.SubordinateRequest> subordinateRequest;

    /**
     * Gets the value of the subordinateRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subordinateRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubordinateRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubordinateDetailType.SubordinateRequest }
     * 
     * 
     */
    public List<SubordinateDetailType.SubordinateRequest> getSubordinateRequest() {
        if (subordinateRequest == null) {
            subordinateRequest = new ArrayList<SubordinateDetailType.SubordinateRequest>();
        }
        return this.subordinateRequest;
    }

    public boolean isSetSubordinateRequest() {
        return ((this.subordinateRequest!= null)&&(!this.subordinateRequest.isEmpty()));
    }

    public void unsetSubordinateRequest() {
        this.subordinateRequest = null;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SubordinateRequestNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}RequestCodeType"/>
     *         &lt;element name="FilledItem" type="{http://nwcg.gov/services/ross/common_types/1.1}FillDetailType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subordinateRequestNumber",
        "filledItem"
    })
    public static class SubordinateRequest {

        @XmlElement(name = "SubordinateRequestNumber", required = true)
        protected RequestCodeType subordinateRequestNumber;
        @XmlElement(name = "FilledItem", required = true)
        protected FillDetailType filledItem;

        /**
         * Gets the value of the subordinateRequestNumber property.
         * 
         * @return
         *     possible object is
         *     {@link RequestCodeType }
         *     
         */
        public RequestCodeType getSubordinateRequestNumber() {
            return subordinateRequestNumber;
        }

        /**
         * Sets the value of the subordinateRequestNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestCodeType }
         *     
         */
        public void setSubordinateRequestNumber(RequestCodeType value) {
            this.subordinateRequestNumber = value;
        }

        public boolean isSetSubordinateRequestNumber() {
            return (this.subordinateRequestNumber!= null);
        }

        /**
         * Gets the value of the filledItem property.
         * 
         * @return
         *     possible object is
         *     {@link FillDetailType }
         *     
         */
        public FillDetailType getFilledItem() {
            return filledItem;
        }

        /**
         * Sets the value of the filledItem property.
         * 
         * @param value
         *     allowed object is
         *     {@link FillDetailType }
         *     
         */
        public void setFilledItem(FillDetailType value) {
            this.filledItem = value;
        }

        public boolean isSetFilledItem() {
            return (this.filledItem!= null);
        }

    }

}
