//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Details on items substituted by external cache
 * 
 * <p>Java class for SubstitutionDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstitutionDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompleteFlag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UserDocumentation" type="{http://nwcg.gov/services/ross/common_types/1.1}DocumentationTextSimpleType"/>
 *         &lt;element name="SubstitutionLine" type="{http://nwcg.gov/services/ross/common_types/1.1}SubstitutionLineType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstitutionDetailType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "completeFlag",
    "userDocumentation",
    "substitutionLine"
})
public class SubstitutionDetailType {

    @XmlElement(name = "CompleteFlag")
    protected boolean completeFlag;
    @XmlElement(name = "UserDocumentation", required = true)
    protected String userDocumentation;
    @XmlElement(name = "SubstitutionLine", required = true)
    protected List<SubstitutionLineType> substitutionLine;

    /**
     * Gets the value of the completeFlag property.
     * 
     */
    public boolean isCompleteFlag() {
        return completeFlag;
    }

    /**
     * Sets the value of the completeFlag property.
     * 
     */
    public void setCompleteFlag(boolean value) {
        this.completeFlag = value;
    }

    public boolean isSetCompleteFlag() {
        return true;
    }

    /**
     * Gets the value of the userDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDocumentation() {
        return userDocumentation;
    }

    /**
     * Sets the value of the userDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDocumentation(String value) {
        this.userDocumentation = value;
    }

    public boolean isSetUserDocumentation() {
        return (this.userDocumentation!= null);
    }

    /**
     * Gets the value of the substitutionLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substitutionLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstitutionLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstitutionLineType }
     * 
     * 
     */
    public List<SubstitutionLineType> getSubstitutionLine() {
        if (substitutionLine == null) {
            substitutionLine = new ArrayList<SubstitutionLineType>();
        }
        return this.substitutionLine;
    }

    public boolean isSetSubstitutionLine() {
        return ((this.substitutionLine!= null)&&(!this.substitutionLine.isEmpty()));
    }

    public void unsetSubstitutionLine() {
        this.substitutionLine = null;
    }

}
