//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing location data in Universal Transverse Mercator (UTM) format.  Datum WGS84/NAD83. 
 * 
 * <p>Java class for UTMCoordinateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UTMCoordinateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UTMGridZoneID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UTMEastingValue">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="160000"/>
 *               &lt;maxInclusive value="834139"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UTMNorthingValue">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="10000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Hemisphere" type="{http://nwcg.gov/services/ross/common_types/1.1}LatitudeDirectionSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UTMCoordinateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "utmGridZoneID",
    "utmEastingValue",
    "utmNorthingValue",
    "hemisphere"
})
public class UTMCoordinateType {

    @XmlElement(name = "UTMGridZoneID", required = true)
    protected String utmGridZoneID;
    @XmlElement(name = "UTMEastingValue", required = true)
    protected BigDecimal utmEastingValue;
    @XmlElement(name = "UTMNorthingValue", required = true)
    protected BigDecimal utmNorthingValue;
    @XmlElement(name = "Hemisphere")
    protected LatitudeDirectionSimpleType hemisphere;

    /**
     * Gets the value of the utmGridZoneID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUTMGridZoneID() {
        return utmGridZoneID;
    }

    /**
     * Sets the value of the utmGridZoneID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUTMGridZoneID(String value) {
        this.utmGridZoneID = value;
    }

    public boolean isSetUTMGridZoneID() {
        return (this.utmGridZoneID!= null);
    }

    /**
     * Gets the value of the utmEastingValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUTMEastingValue() {
        return utmEastingValue;
    }

    /**
     * Sets the value of the utmEastingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUTMEastingValue(BigDecimal value) {
        this.utmEastingValue = value;
    }

    public boolean isSetUTMEastingValue() {
        return (this.utmEastingValue!= null);
    }

    /**
     * Gets the value of the utmNorthingValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUTMNorthingValue() {
        return utmNorthingValue;
    }

    /**
     * Sets the value of the utmNorthingValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUTMNorthingValue(BigDecimal value) {
        this.utmNorthingValue = value;
    }

    public boolean isSetUTMNorthingValue() {
        return (this.utmNorthingValue!= null);
    }

    /**
     * Gets the value of the hemisphere property.
     * 
     * @return
     *     possible object is
     *     {@link LatitudeDirectionSimpleType }
     *     
     */
    public LatitudeDirectionSimpleType getHemisphere() {
        return hemisphere;
    }

    /**
     * Sets the value of the hemisphere property.
     * 
     * @param value
     *     allowed object is
     *     {@link LatitudeDirectionSimpleType }
     *     
     */
    public void setHemisphere(LatitudeDirectionSimpleType value) {
        this.hemisphere = value;
    }

    public boolean isSetHemisphere() {
        return (this.hemisphere!= null);
    }

}
