//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.catalog.wsdl._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

@WebServiceClient(name = "CatalogService", targetNamespace = "http://nwcg.gov/services/ross/catalog/wsdl/1.1", wsdlLocation = "WEB-INF/wsdl/Catalog.wsdl")
public class CatalogService
    extends Service
{

    private final static URL CATALOGSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("WEB-INF/wsdl/Catalog.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CATALOGSERVICE_WSDL_LOCATION = url;
    }

    public CatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CatalogService() {
        super(CATALOGSERVICE_WSDL_LOCATION, new QName("http://nwcg.gov/services/ross/catalog/wsdl/1.1", "CatalogService"));
    }

    /**
     * Integration Test Endpoint
     * 
     * @return
     *     returns CatalogInterface
     */
    @WebEndpoint(name = "CatalogPort")
    public CatalogInterface getCatalogPort() {
        return (CatalogInterface)super.getPort(new QName("http://nwcg.gov/services/ross/catalog/wsdl/1.1", "CatalogPort"), CatalogInterface.class);
    }

}
