//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddressTypeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AddressTypeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Mailing"/>
 *     &lt;enumeration value="Shipping"/>
 *     &lt;enumeration value="Official"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
@XmlType(name = "AddressTypeSimpleType", namespace = "http://nwcg.gov/services/ross/common_types/1.1")
public enum AddressTypeSimpleType {

    @XmlEnumValue("Mailing")
    MAILING("Mailing"),
    @XmlEnumValue("Shipping")
    SHIPPING("Shipping"),
    @XmlEnumValue("Official")
    OFFICIAL("Official");
    private final String value;

    AddressTypeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddressTypeSimpleType fromValue(String v) {
        for (AddressTypeSimpleType c: AddressTypeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
