//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing the attributes used to identify an airport
 * 
 * <p>Java class for AirportNaturalKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AirportNaturalKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="AirportFAACode" type="{http://nwcg.gov/services/ross/common_types/1.1}FAACodeSimpleType"/>
 *         &lt;element name="AirportName" type="{http://nwcg.gov/services/ross/common_types/1.1}AirportNameSimpleType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AirportNaturalKeyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "airportFAACode",
    "airportName"
})
public class AirportNaturalKeyType {

    @XmlElement(name = "AirportFAACode")
    protected String airportFAACode;
    @XmlElement(name = "AirportName")
    protected String airportName;

    /**
     * Gets the value of the airportFAACode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportFAACode() {
        return airportFAACode;
    }

    /**
     * Sets the value of the airportFAACode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportFAACode(String value) {
        this.airportFAACode = value;
    }

    public boolean isSetAirportFAACode() {
        return (this.airportFAACode!= null);
    }

    /**
     * Gets the value of the airportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportName() {
        return airportName;
    }

    /**
     * Sets the value of the airportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportName(String value) {
        this.airportName = value;
    }

    public boolean isSetAirportName() {
        return (this.airportName!= null);
    }

}
