//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Facilitates the sending of changed attributes only during an update notification.
 * 
 * <p>Java class for AttributeChangedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeChangedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EntityType">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://nwcg.gov/services/ross/common_types/1.1>EntityTypeSimpleType">
 *                 &lt;attribute name="EntityTypeName" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="Resource"/>
 *                       &lt;enumeration value="Incident"/>
 *                       &lt;enumeration value="ResourceRequest"/>
 *                       &lt;enumeration value="IncidentAviationHazard"/>
 *                       &lt;enumeration value="IncidentRadioFrequency"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;choice>
 *           &lt;element name="IncidentAttributeType">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="IncidentAttributeTypeName" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="IncidentName"/>
 *                         &lt;enumeration value="IncidentType"/>
 *                         &lt;enumeration value="LocationName"/>
 *                         &lt;enumeration value="OfficeReferenceNumber"/>
 *                         &lt;enumeration value="InitialDateTime"/>
 *                         &lt;enumeration value="Description"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="IncidentRadioFrequencyAttributeType">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="IncidentRadioFrequencyAttributeTypeName" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="FrequencyValue"/>
 *                         &lt;enumeration value="FrequencyType"/>
 *                         &lt;enumeration value="IsPrimaryIndicator"/>
 *                         &lt;enumeration value="Tone"/>
 *                         &lt;enumeration value="IsTacticalIndicator"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="IncidentAviationHazardAttributeType">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="IncidentAviationHazardAttributeTypeName" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="HazardType"/>
 *                         &lt;enumeration value="City"/>
 *                         &lt;enumeration value="State"/>
 *                         &lt;enumeration value="Description"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ResourceRequestAttributeType">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="ResourceRequestAttributeTypeName" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="NeedDateTime"/>
 *                         &lt;enumeration value="RequestedItemName"/>
 *                         &lt;enumeration value="InclusionType"/>
 *                         &lt;enumeration value="SpecialNeedsIndicator"/>
 *                         &lt;enumeration value="NamedRequestIndicator"/>
 *                         &lt;enumeration value="Priority"/>
 *                         &lt;enumeration value="MethodForPerson"/>
 *                         &lt;enumeration value="MethodForOrganization"/>
 *                         &lt;enumeration value="Description"/>
 *                         &lt;enumeration value="Date"/>
 *                         &lt;enumeration value="SystemName"/>
 *                         &lt;enumeration value="DispatchUnitID"/>
 *                         &lt;enumeration value="Author"/>
 *                         &lt;enumeration value="Text"/>
 *                         &lt;enumeration value="Name"/>
 *                         &lt;enumeration value="LocationType"/>
 *                         &lt;enumeration value="State"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="ResourceAttributeType">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;attribute name="ResourceAttributeTypeName" use="required">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/attribute>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="NewAttributeValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeChangedType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "entityType",
    "incidentAttributeType",
    "incidentRadioFrequencyAttributeType",
    "incidentAviationHazardAttributeType",
    "resourceRequestAttributeType",
    "resourceAttributeType",
    "newAttributeValue"
})
public class AttributeChangedType {

    @XmlElement(name = "EntityType", required = true)
    protected AttributeChangedType.EntityType entityType;
    @XmlElement(name = "IncidentAttributeType")
    protected AttributeChangedType.IncidentAttributeType incidentAttributeType;
    @XmlElement(name = "IncidentRadioFrequencyAttributeType")
    protected AttributeChangedType.IncidentRadioFrequencyAttributeType incidentRadioFrequencyAttributeType;
    @XmlElement(name = "IncidentAviationHazardAttributeType")
    protected AttributeChangedType.IncidentAviationHazardAttributeType incidentAviationHazardAttributeType;
    @XmlElement(name = "ResourceRequestAttributeType")
    protected AttributeChangedType.ResourceRequestAttributeType resourceRequestAttributeType;
    @XmlElement(name = "ResourceAttributeType")
    protected AttributeChangedType.ResourceAttributeType resourceAttributeType;
    @XmlElement(name = "NewAttributeValue", required = true)
    protected String newAttributeValue;

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChangedType.EntityType }
     *     
     */
    public AttributeChangedType.EntityType getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChangedType.EntityType }
     *     
     */
    public void setEntityType(AttributeChangedType.EntityType value) {
        this.entityType = value;
    }

    public boolean isSetEntityType() {
        return (this.entityType!= null);
    }

    /**
     * Gets the value of the incidentAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChangedType.IncidentAttributeType }
     *     
     */
    public AttributeChangedType.IncidentAttributeType getIncidentAttributeType() {
        return incidentAttributeType;
    }

    /**
     * Sets the value of the incidentAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChangedType.IncidentAttributeType }
     *     
     */
    public void setIncidentAttributeType(AttributeChangedType.IncidentAttributeType value) {
        this.incidentAttributeType = value;
    }

    public boolean isSetIncidentAttributeType() {
        return (this.incidentAttributeType!= null);
    }

    /**
     * Gets the value of the incidentRadioFrequencyAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChangedType.IncidentRadioFrequencyAttributeType }
     *     
     */
    public AttributeChangedType.IncidentRadioFrequencyAttributeType getIncidentRadioFrequencyAttributeType() {
        return incidentRadioFrequencyAttributeType;
    }

    /**
     * Sets the value of the incidentRadioFrequencyAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChangedType.IncidentRadioFrequencyAttributeType }
     *     
     */
    public void setIncidentRadioFrequencyAttributeType(AttributeChangedType.IncidentRadioFrequencyAttributeType value) {
        this.incidentRadioFrequencyAttributeType = value;
    }

    public boolean isSetIncidentRadioFrequencyAttributeType() {
        return (this.incidentRadioFrequencyAttributeType!= null);
    }

    /**
     * Gets the value of the incidentAviationHazardAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChangedType.IncidentAviationHazardAttributeType }
     *     
     */
    public AttributeChangedType.IncidentAviationHazardAttributeType getIncidentAviationHazardAttributeType() {
        return incidentAviationHazardAttributeType;
    }

    /**
     * Sets the value of the incidentAviationHazardAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChangedType.IncidentAviationHazardAttributeType }
     *     
     */
    public void setIncidentAviationHazardAttributeType(AttributeChangedType.IncidentAviationHazardAttributeType value) {
        this.incidentAviationHazardAttributeType = value;
    }

    public boolean isSetIncidentAviationHazardAttributeType() {
        return (this.incidentAviationHazardAttributeType!= null);
    }

    /**
     * Gets the value of the resourceRequestAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChangedType.ResourceRequestAttributeType }
     *     
     */
    public AttributeChangedType.ResourceRequestAttributeType getResourceRequestAttributeType() {
        return resourceRequestAttributeType;
    }

    /**
     * Sets the value of the resourceRequestAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChangedType.ResourceRequestAttributeType }
     *     
     */
    public void setResourceRequestAttributeType(AttributeChangedType.ResourceRequestAttributeType value) {
        this.resourceRequestAttributeType = value;
    }

    public boolean isSetResourceRequestAttributeType() {
        return (this.resourceRequestAttributeType!= null);
    }

    /**
     * Gets the value of the resourceAttributeType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeChangedType.ResourceAttributeType }
     *     
     */
    public AttributeChangedType.ResourceAttributeType getResourceAttributeType() {
        return resourceAttributeType;
    }

    /**
     * Sets the value of the resourceAttributeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeChangedType.ResourceAttributeType }
     *     
     */
    public void setResourceAttributeType(AttributeChangedType.ResourceAttributeType value) {
        this.resourceAttributeType = value;
    }

    public boolean isSetResourceAttributeType() {
        return (this.resourceAttributeType!= null);
    }

    /**
     * Gets the value of the newAttributeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewAttributeValue() {
        return newAttributeValue;
    }

    /**
     * Sets the value of the newAttributeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewAttributeValue(String value) {
        this.newAttributeValue = value;
    }

    public boolean isSetNewAttributeValue() {
        return (this.newAttributeValue!= null);
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://nwcg.gov/services/ross/common_types/1.1>EntityTypeSimpleType">
     *       &lt;attribute name="EntityTypeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="Resource"/>
     *             &lt;enumeration value="Incident"/>
     *             &lt;enumeration value="ResourceRequest"/>
     *             &lt;enumeration value="IncidentAviationHazard"/>
     *             &lt;enumeration value="IncidentRadioFrequency"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class EntityType {

        @XmlValue
        protected EntityTypeSimpleType value;
        @XmlAttribute(name = "EntityTypeName", required = true)
        protected String entityTypeName;

        /**
         *  2.6 - Enumerated list of entity types such as RadioFrequency, Incident etc
         * 
         * @return
         *     possible object is
         *     {@link EntityTypeSimpleType }
         *     
         */
        public EntityTypeSimpleType getValue() {
            return value;
        }

        /**
         *  2.6 - Enumerated list of entity types such as RadioFrequency, Incident etc
         * 
         * @param value
         *     allowed object is
         *     {@link EntityTypeSimpleType }
         *     
         */
        public void setValue(EntityTypeSimpleType value) {
            this.value = value;
        }

        public boolean isSetValue() {
            return (this.value!= null);
        }

        /**
         * Gets the value of the entityTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEntityTypeName() {
            return entityTypeName;
        }

        /**
         * Sets the value of the entityTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEntityTypeName(String value) {
            this.entityTypeName = value;
        }

        public boolean isSetEntityTypeName() {
            return (this.entityTypeName!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="IncidentAttributeTypeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="IncidentName"/>
     *             &lt;enumeration value="IncidentType"/>
     *             &lt;enumeration value="LocationName"/>
     *             &lt;enumeration value="OfficeReferenceNumber"/>
     *             &lt;enumeration value="InitialDateTime"/>
     *             &lt;enumeration value="Description"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncidentAttributeType {

        @XmlAttribute(name = "IncidentAttributeTypeName", required = true)
        protected String incidentAttributeTypeName;

        /**
         * Gets the value of the incidentAttributeTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIncidentAttributeTypeName() {
            return incidentAttributeTypeName;
        }

        /**
         * Sets the value of the incidentAttributeTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIncidentAttributeTypeName(String value) {
            this.incidentAttributeTypeName = value;
        }

        public boolean isSetIncidentAttributeTypeName() {
            return (this.incidentAttributeTypeName!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="IncidentAviationHazardAttributeTypeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="HazardType"/>
     *             &lt;enumeration value="City"/>
     *             &lt;enumeration value="State"/>
     *             &lt;enumeration value="Description"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncidentAviationHazardAttributeType {

        @XmlAttribute(name = "IncidentAviationHazardAttributeTypeName", required = true)
        protected String incidentAviationHazardAttributeTypeName;

        /**
         * Gets the value of the incidentAviationHazardAttributeTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIncidentAviationHazardAttributeTypeName() {
            return incidentAviationHazardAttributeTypeName;
        }

        /**
         * Sets the value of the incidentAviationHazardAttributeTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIncidentAviationHazardAttributeTypeName(String value) {
            this.incidentAviationHazardAttributeTypeName = value;
        }

        public boolean isSetIncidentAviationHazardAttributeTypeName() {
            return (this.incidentAviationHazardAttributeTypeName!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="IncidentRadioFrequencyAttributeTypeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="FrequencyValue"/>
     *             &lt;enumeration value="FrequencyType"/>
     *             &lt;enumeration value="IsPrimaryIndicator"/>
     *             &lt;enumeration value="Tone"/>
     *             &lt;enumeration value="IsTacticalIndicator"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IncidentRadioFrequencyAttributeType {

        @XmlAttribute(name = "IncidentRadioFrequencyAttributeTypeName", required = true)
        protected String incidentRadioFrequencyAttributeTypeName;

        /**
         * Gets the value of the incidentRadioFrequencyAttributeTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIncidentRadioFrequencyAttributeTypeName() {
            return incidentRadioFrequencyAttributeTypeName;
        }

        /**
         * Sets the value of the incidentRadioFrequencyAttributeTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIncidentRadioFrequencyAttributeTypeName(String value) {
            this.incidentRadioFrequencyAttributeTypeName = value;
        }

        public boolean isSetIncidentRadioFrequencyAttributeTypeName() {
            return (this.incidentRadioFrequencyAttributeTypeName!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ResourceAttributeTypeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ResourceAttributeType {

        @XmlAttribute(name = "ResourceAttributeTypeName", required = true)
        protected String resourceAttributeTypeName;

        /**
         * Gets the value of the resourceAttributeTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceAttributeTypeName() {
            return resourceAttributeTypeName;
        }

        /**
         * Sets the value of the resourceAttributeTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceAttributeTypeName(String value) {
            this.resourceAttributeTypeName = value;
        }

        public boolean isSetResourceAttributeTypeName() {
            return (this.resourceAttributeTypeName!= null);
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="ResourceRequestAttributeTypeName" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="NeedDateTime"/>
     *             &lt;enumeration value="RequestedItemName"/>
     *             &lt;enumeration value="InclusionType"/>
     *             &lt;enumeration value="SpecialNeedsIndicator"/>
     *             &lt;enumeration value="NamedRequestIndicator"/>
     *             &lt;enumeration value="Priority"/>
     *             &lt;enumeration value="MethodForPerson"/>
     *             &lt;enumeration value="MethodForOrganization"/>
     *             &lt;enumeration value="Description"/>
     *             &lt;enumeration value="Date"/>
     *             &lt;enumeration value="SystemName"/>
     *             &lt;enumeration value="DispatchUnitID"/>
     *             &lt;enumeration value="Author"/>
     *             &lt;enumeration value="Text"/>
     *             &lt;enumeration value="Name"/>
     *             &lt;enumeration value="LocationType"/>
     *             &lt;enumeration value="State"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ResourceRequestAttributeType {

        @XmlAttribute(name = "ResourceRequestAttributeTypeName", required = true)
        protected String resourceRequestAttributeTypeName;

        /**
         * Gets the value of the resourceRequestAttributeTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceRequestAttributeTypeName() {
            return resourceRequestAttributeTypeName;
        }

        /**
         * Sets the value of the resourceRequestAttributeTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceRequestAttributeTypeName(String value) {
            this.resourceRequestAttributeTypeName = value;
        }

        public boolean isSetResourceRequestAttributeTypeName() {
            return (this.resourceRequestAttributeTypeName!= null);
        }

    }

}
