//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing the attributes that identify a catalog item
 * 
 * <p>Java class for CatalogItemNaturalKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatalogItemNaturalKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogType" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogTypeSimpleType"/>
 *         &lt;choice>
 *           &lt;element name="CatalogItemName" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemDescriptionSimpleType"/>
 *           &lt;element name="CatalogItemCode" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemMnemonicSimpleType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatalogItemNaturalKeyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "catalogType",
    "catalogItemName",
    "catalogItemCode"
})
public class CatalogItemNaturalKeyType {

    @XmlElement(name = "CatalogType", required = true)
    protected CatalogTypeSimpleType catalogType;
    @XmlElement(name = "CatalogItemName")
    protected String catalogItemName;
    @XmlElement(name = "CatalogItemCode")
    protected String catalogItemCode;

    /**
     * Gets the value of the catalogType property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogTypeSimpleType }
     *     
     */
    public CatalogTypeSimpleType getCatalogType() {
        return catalogType;
    }

    /**
     * Sets the value of the catalogType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogTypeSimpleType }
     *     
     */
    public void setCatalogType(CatalogTypeSimpleType value) {
        this.catalogType = value;
    }

    public boolean isSetCatalogType() {
        return (this.catalogType!= null);
    }

    /**
     * Gets the value of the catalogItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemName() {
        return catalogItemName;
    }

    /**
     * Sets the value of the catalogItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemName(String value) {
        this.catalogItemName = value;
    }

    public boolean isSetCatalogItemName() {
        return (this.catalogItemName!= null);
    }

    /**
     * Gets the value of the catalogItemCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogItemCode() {
        return catalogItemCode;
    }

    /**
     * Sets the value of the catalogItemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogItemCode(String value) {
        this.catalogItemCode = value;
    }

    public boolean isSetCatalogItemCode() {
        return (this.catalogItemCode!= null);
    }

}
