//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Documentation for incidents, resources or other objects
 * 
 * <p>Java class for DocumentationReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentationReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="SystemName" type="{http://nwcg.gov/services/ross/common_types/1.1}SystemTypeSimpleType"/>
 *         &lt;element name="DispatchUnitID" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType"/>
 *         &lt;element name="Author">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Text" type="{http://nwcg.gov/services/ross/common_types/1.1}DocumentationTextSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentationReturnType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "date",
    "systemName",
    "dispatchUnitID",
    "author",
    "text"
})
public class DocumentationReturnType {

    @XmlElement(name = "Date", required = true)
    protected XMLGregorianCalendar date;
    @XmlElement(name = "SystemName", required = true)
    protected SystemTypeSimpleType systemName;
    @XmlElement(name = "DispatchUnitID", required = true)
    protected UnitIDType dispatchUnitID;
    @XmlElement(name = "Author", required = true)
    protected String author;
    @XmlElement(name = "Text", required = true)
    protected String text;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    public boolean isSetDate() {
        return (this.date!= null);
    }

    /**
     * Gets the value of the systemName property.
     * 
     * @return
     *     possible object is
     *     {@link SystemTypeSimpleType }
     *     
     */
    public SystemTypeSimpleType getSystemName() {
        return systemName;
    }

    /**
     * Sets the value of the systemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemTypeSimpleType }
     *     
     */
    public void setSystemName(SystemTypeSimpleType value) {
        this.systemName = value;
    }

    public boolean isSetSystemName() {
        return (this.systemName!= null);
    }

    /**
     * Gets the value of the dispatchUnitID property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getDispatchUnitID() {
        return dispatchUnitID;
    }

    /**
     * Sets the value of the dispatchUnitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setDispatchUnitID(UnitIDType value) {
        this.dispatchUnitID = value;
    }

    public boolean isSetDispatchUnitID() {
        return (this.dispatchUnitID!= null);
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    public boolean isSetAuthor() {
        return (this.author!= null);
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    public boolean isSetText() {
        return (this.text!= null);
    }

}
