//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing financial code attributes
 * 
 * <p>Java class for FinancialCodeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FinancialCodeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Code" type="{http://nwcg.gov/services/ross/common_types/1.1}FinancialCodeSimpleType"/>
 *         &lt;element name="OwningAgencyName" type="{http://nwcg.gov/services/ross/common_types/1.1}OrganizationNameSimpleType"/>
 *         &lt;element name="FiscalYear" type="{http://nwcg.gov/services/ross/common_types/1.1}FiscalYearSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FinancialCodeType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "code",
    "owningAgencyName",
    "fiscalYear"
})
public class FinancialCodeType {

    @XmlElement(name = "Code", required = true)
    protected String code;
    @XmlElement(name = "OwningAgencyName", required = true)
    protected String owningAgencyName;
    @XmlElement(name = "FiscalYear")
    protected int fiscalYear;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    public boolean isSetCode() {
        return (this.code!= null);
    }

    /**
     * Gets the value of the owningAgencyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwningAgencyName() {
        return owningAgencyName;
    }

    /**
     * Sets the value of the owningAgencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwningAgencyName(String value) {
        this.owningAgencyName = value;
    }

    public boolean isSetOwningAgencyName() {
        return (this.owningAgencyName!= null);
    }

    /**
     * Gets the value of the fiscalYear property.
     * 
     */
    public int getFiscalYear() {
        return fiscalYear;
    }

    /**
     * Sets the value of the fiscalYear property.
     * 
     */
    public void setFiscalYear(int value) {
        this.fiscalYear = value;
    }

    public boolean isSetFiscalYear() {
        return true;
    }

}
