//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing attributes that uniquely identify an incident radio frequency
 * 
 * <p>Java class for IncidentRadioFrequencyNaturalKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentRadioFrequencyNaturalKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncidentKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeIncidentKeyType"/>
 *         &lt;element name="FrequencyType" type="{http://nwcg.gov/services/ross/common_types/1.1}RadioFrequencyTypeSimpleType"/>
 *         &lt;element name="FrequencyValue" type="{http://nwcg.gov/services/ross/common_types/1.1}FrequencyValueSimpleType"/>
 *         &lt;element name="Tone" type="{http://nwcg.gov/services/ross/common_types/1.1}FrequencyToneSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentRadioFrequencyNaturalKeyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "incidentKey",
    "frequencyType",
    "frequencyValue",
    "tone"
})
public class IncidentRadioFrequencyNaturalKeyType {

    @XmlElement(name = "IncidentKey", required = true)
    protected CompositeIncidentKeyType incidentKey;
    @XmlElement(name = "FrequencyType", required = true)
    protected String frequencyType;
    @XmlElement(name = "FrequencyValue", required = true)
    protected String frequencyValue;
    @XmlElement(name = "Tone")
    protected Double tone;

    /**
     * Gets the value of the incidentKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public CompositeIncidentKeyType getIncidentKey() {
        return incidentKey;
    }

    /**
     * Sets the value of the incidentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeIncidentKeyType }
     *     
     */
    public void setIncidentKey(CompositeIncidentKeyType value) {
        this.incidentKey = value;
    }

    public boolean isSetIncidentKey() {
        return (this.incidentKey!= null);
    }

    /**
     * Gets the value of the frequencyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequencyType() {
        return frequencyType;
    }

    /**
     * Sets the value of the frequencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequencyType(String value) {
        this.frequencyType = value;
    }

    public boolean isSetFrequencyType() {
        return (this.frequencyType!= null);
    }

    /**
     * Gets the value of the frequencyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequencyValue() {
        return frequencyValue;
    }

    /**
     * Sets the value of the frequencyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequencyValue(String value) {
        this.frequencyValue = value;
    }

    public boolean isSetFrequencyValue() {
        return (this.frequencyValue!= null);
    }

    /**
     * Gets the value of the tone property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTone() {
        return tone;
    }

    /**
     * Sets the value of the tone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTone(Double value) {
        this.tone = value;
    }

    public boolean isSetTone() {
        return (this.tone!= null);
    }

}
