//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing address info for an incident
 * 
 * <p>Java class for IncidentAddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncidentAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://nwcg.gov/services/ross/common_types/1.1}AddressType"/>
 *         &lt;element name="PrimaryInd" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncidentAddressType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "address",
    "primaryInd"
})
public class IncidentAddressType {

    @XmlElement(name = "Address", required = true)
    protected AddressType address;
    @XmlElement(name = "PrimaryInd")
    protected boolean primaryInd;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    public boolean isSetAddress() {
        return (this.address!= null);
    }

    /**
     * Gets the value of the primaryInd property.
     * 
     */
    public boolean isPrimaryInd() {
        return primaryInd;
    }

    /**
     * Sets the value of the primaryInd property.
     * 
     */
    public void setPrimaryInd(boolean value) {
        this.primaryInd = value;
    }

    public boolean isSetPrimaryInd() {
        return true;
    }

}
