//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Strucutre used when building a master roster. Unites a resource with a position.
 * 
 * <p>Java class for MasterRosterPosition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MasterRosterPosition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeResourceKeyType"/>
 *         &lt;element name="CatalogItem" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MasterRosterPosition", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "resourceKey",
    "catalogItem"
})
public class MasterRosterPosition {

    @XmlElement(name = "ResourceKey", required = true)
    protected CompositeResourceKeyType resourceKey;
    @XmlElement(name = "CatalogItem", required = true)
    protected CatalogItemType catalogItem;

    /**
     * Gets the value of the resourceKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeResourceKeyType }
     *     
     */
    public CompositeResourceKeyType getResourceKey() {
        return resourceKey;
    }

    /**
     * Sets the value of the resourceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeResourceKeyType }
     *     
     */
    public void setResourceKey(CompositeResourceKeyType value) {
        this.resourceKey = value;
    }

    public boolean isSetResourceKey() {
        return (this.resourceKey!= null);
    }

    /**
     * Gets the value of the catalogItem property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogItemType }
     *     
     */
    public CatalogItemType getCatalogItem() {
        return catalogItem;
    }

    /**
     * Sets the value of the catalogItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogItemType }
     *     
     */
    public void setCatalogItem(CatalogItemType value) {
        this.catalogItem = value;
    }

    public boolean isSetCatalogItem() {
        return (this.catalogItem!= null);
    }

}
