//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 *  2.6 - Information identifying where the request originated
 * 
 * <p>Java class for MessageOriginatorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageOriginatorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SystemOfOrigin" type="{http://nwcg.gov/services/ross/common_types/1.1}ApplicationSystemType"/>
 *         &lt;element name="DispatchUnitID" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageOriginatorType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "systemOfOrigin",
    "dispatchUnitID"
})
public class MessageOriginatorType {

    @XmlElement(name = "SystemOfOrigin", required = true)
    protected ApplicationSystemType systemOfOrigin;
    @XmlElement(name = "DispatchUnitID")
    protected UnitIDType dispatchUnitID;

    /**
     * Gets the value of the systemOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationSystemType }
     *     
     */
    public ApplicationSystemType getSystemOfOrigin() {
        return systemOfOrigin;
    }

    /**
     * Sets the value of the systemOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationSystemType }
     *     
     */
    public void setSystemOfOrigin(ApplicationSystemType value) {
        this.systemOfOrigin = value;
    }

    public boolean isSetSystemOfOrigin() {
        return (this.systemOfOrigin!= null);
    }

    /**
     * Gets the value of the dispatchUnitID property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getDispatchUnitID() {
        return dispatchUnitID;
    }

    /**
     * Sets the value of the dispatchUnitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setDispatchUnitID(UnitIDType value) {
        this.dispatchUnitID = value;
    }

    public boolean isSetDispatchUnitID() {
        return (this.dispatchUnitID!= null);
    }

}
