//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReassignedRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReassignedRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReassignFromRequest" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeResourceRequestKeyType"/>
 *         &lt;element name="ReassignToRequest" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestCreateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReassignedRequestType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "reassignFromRequest",
    "reassignToRequest"
})
public class ReassignedRequestType {

    @XmlElement(name = "ReassignFromRequest", required = true)
    protected CompositeResourceRequestKeyType reassignFromRequest;
    @XmlElement(name = "ReassignToRequest", required = true)
    protected ResourceRequestCreateType reassignToRequest;

    /**
     * Gets the value of the reassignFromRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeResourceRequestKeyType }
     *     
     */
    public CompositeResourceRequestKeyType getReassignFromRequest() {
        return reassignFromRequest;
    }

    /**
     * Sets the value of the reassignFromRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeResourceRequestKeyType }
     *     
     */
    public void setReassignFromRequest(CompositeResourceRequestKeyType value) {
        this.reassignFromRequest = value;
    }

    public boolean isSetReassignFromRequest() {
        return (this.reassignFromRequest!= null);
    }

    /**
     * Gets the value of the reassignToRequest property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRequestCreateType }
     *     
     */
    public ResourceRequestCreateType getReassignToRequest() {
        return reassignToRequest;
    }

    /**
     * Sets the value of the reassignToRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRequestCreateType }
     *     
     */
    public void setReassignToRequest(ResourceRequestCreateType value) {
        this.reassignToRequest = value;
    }

    public boolean isSetReassignToRequest() {
        return (this.reassignToRequest!= null);
    }

}
