//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Structure containing resource request information used during creation
 * 
 * <p>Java class for ResourceRequestCreateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceRequestCreateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="RequestedCatalogItem" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemType"/>
 *           &lt;element name="RequestedItemKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemNaturalKeyType"/>
 *         &lt;/choice>
 *         &lt;element name="NeedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DeliverToLocation" type="{http://nwcg.gov/services/ross/common_types/1.1}DeliverToLocationCreateType" minOccurs="0"/>
 *         &lt;element name="RequestingContactInfo" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestContactInfoSimpleType" minOccurs="0"/>
 *         &lt;element name="InclusionType" type="{http://nwcg.gov/services/ross/common_types/1.1}RequestInclusionSimpleType" minOccurs="0"/>
 *         &lt;element name="Restrictions" type="{http://nwcg.gov/services/ross/common_types/1.1}RequestRestrictionSimpleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ReloadBaseFAACode" type="{http://nwcg.gov/services/ross/common_types/1.1}FAACodeSimpleType" minOccurs="0"/>
 *         &lt;element name="SequenceNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogSequenceNumber" minOccurs="0"/>
 *         &lt;element name="QuantityRequested" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://nwcg.gov/services/ross/common_types/1.1}QuantitySimpleType">
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FinancialCode" type="{http://nwcg.gov/services/ross/common_types/1.1}FinancialCodeType" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="ShippingAddress" type="{http://nwcg.gov/services/ross/common_types/1.1}AddressType"/>
 *           &lt;element name="ShippingInstructions" type="{http://nwcg.gov/services/ross/common_types/1.1}ShippingInstructionsCreateType"/>
 *           &lt;element name="WillPickUpInfo" type="{http://nwcg.gov/services/ross/common_types/1.1}WillPickUpInformationType"/>
 *         &lt;/choice>
 *         &lt;element name="ShippingContactName" type="{http://nwcg.gov/services/ross/common_types/1.1}ShippingContactNameSimpleType" minOccurs="0"/>
 *         &lt;element name="ShippingContactPhone" type="{http://nwcg.gov/services/ross/common_types/1.1}ShippingContactPhoneSimpleType" minOccurs="0"/>
 *         &lt;element name="ReplacementInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SpecialNeeds" type="{http://nwcg.gov/services/ross/common_types/1.1}SpecialNeedsSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceRequestCreateType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "requestedCatalogItem",
    "requestedItemKey",
    "needDateTime",
    "deliverToLocation",
    "requestingContactInfo",
    "inclusionType",
    "restrictions",
    "reloadBaseFAACode",
    "sequenceNumber",
    "quantityRequested",
    "financialCode",
    "shippingAddress",
    "shippingInstructions",
    "willPickUpInfo",
    "shippingContactName",
    "shippingContactPhone",
    "replacementInd",
    "specialNeeds"
})
public class ResourceRequestCreateType {

    @XmlElement(name = "RequestedCatalogItem")
    protected CatalogItemType requestedCatalogItem;
    @XmlElement(name = "RequestedItemKey")
    protected CatalogItemNaturalKeyType requestedItemKey;
    @XmlElement(name = "NeedDateTime", required = true)
    protected XMLGregorianCalendar needDateTime;
    @XmlElement(name = "DeliverToLocation")
    protected DeliverToLocationCreateType deliverToLocation;
    @XmlElement(name = "RequestingContactInfo")
    protected String requestingContactInfo;
    @XmlElement(name = "InclusionType", defaultValue = "None")
    protected RequestInclusionSimpleType inclusionType;
    @XmlElement(name = "Restrictions")
    protected List<RequestRestrictionSimpleType> restrictions;
    @XmlElement(name = "ReloadBaseFAACode")
    protected String reloadBaseFAACode;
    @XmlElement(name = "SequenceNumber")
    protected String sequenceNumber;
    @XmlElement(name = "QuantityRequested")
    protected Integer quantityRequested;
    @XmlElement(name = "FinancialCode")
    protected FinancialCodeType financialCode;
    @XmlElement(name = "ShippingAddress")
    protected AddressType shippingAddress;
    @XmlElement(name = "ShippingInstructions")
    protected ShippingInstructionsCreateType shippingInstructions;
    @XmlElement(name = "WillPickUpInfo")
    protected WillPickUpInformationType willPickUpInfo;
    @XmlElement(name = "ShippingContactName")
    protected String shippingContactName;
    @XmlElement(name = "ShippingContactPhone")
    protected String shippingContactPhone;
    @XmlElement(name = "ReplacementInd")
    protected Boolean replacementInd;
    @XmlElement(name = "SpecialNeeds")
    protected String specialNeeds;

    /**
     * Gets the value of the requestedCatalogItem property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogItemType }
     *     
     */
    public CatalogItemType getRequestedCatalogItem() {
        return requestedCatalogItem;
    }

    /**
     * Sets the value of the requestedCatalogItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogItemType }
     *     
     */
    public void setRequestedCatalogItem(CatalogItemType value) {
        this.requestedCatalogItem = value;
    }

    public boolean isSetRequestedCatalogItem() {
        return (this.requestedCatalogItem!= null);
    }

    /**
     * Gets the value of the requestedItemKey property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogItemNaturalKeyType }
     *     
     */
    public CatalogItemNaturalKeyType getRequestedItemKey() {
        return requestedItemKey;
    }

    /**
     * Sets the value of the requestedItemKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogItemNaturalKeyType }
     *     
     */
    public void setRequestedItemKey(CatalogItemNaturalKeyType value) {
        this.requestedItemKey = value;
    }

    public boolean isSetRequestedItemKey() {
        return (this.requestedItemKey!= null);
    }

    /**
     * Gets the value of the needDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNeedDateTime() {
        return needDateTime;
    }

    /**
     * Sets the value of the needDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNeedDateTime(XMLGregorianCalendar value) {
        this.needDateTime = value;
    }

    public boolean isSetNeedDateTime() {
        return (this.needDateTime!= null);
    }

    /**
     * Gets the value of the deliverToLocation property.
     * 
     * @return
     *     possible object is
     *     {@link DeliverToLocationCreateType }
     *     
     */
    public DeliverToLocationCreateType getDeliverToLocation() {
        return deliverToLocation;
    }

    /**
     * Sets the value of the deliverToLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliverToLocationCreateType }
     *     
     */
    public void setDeliverToLocation(DeliverToLocationCreateType value) {
        this.deliverToLocation = value;
    }

    public boolean isSetDeliverToLocation() {
        return (this.deliverToLocation!= null);
    }

    /**
     * Gets the value of the requestingContactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestingContactInfo() {
        return requestingContactInfo;
    }

    /**
     * Sets the value of the requestingContactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestingContactInfo(String value) {
        this.requestingContactInfo = value;
    }

    public boolean isSetRequestingContactInfo() {
        return (this.requestingContactInfo!= null);
    }

    /**
     * Gets the value of the inclusionType property.
     * 
     * @return
     *     possible object is
     *     {@link RequestInclusionSimpleType }
     *     
     */
    public RequestInclusionSimpleType getInclusionType() {
        return inclusionType;
    }

    /**
     * Sets the value of the inclusionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestInclusionSimpleType }
     *     
     */
    public void setInclusionType(RequestInclusionSimpleType value) {
        this.inclusionType = value;
    }

    public boolean isSetInclusionType() {
        return (this.inclusionType!= null);
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RequestRestrictionSimpleType }
     * 
     * 
     */
    public List<RequestRestrictionSimpleType> getRestrictions() {
        if (restrictions == null) {
            restrictions = new ArrayList<RequestRestrictionSimpleType>();
        }
        return this.restrictions;
    }

    public boolean isSetRestrictions() {
        return ((this.restrictions!= null)&&(!this.restrictions.isEmpty()));
    }

    public void unsetRestrictions() {
        this.restrictions = null;
    }

    /**
     * Gets the value of the reloadBaseFAACode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReloadBaseFAACode() {
        return reloadBaseFAACode;
    }

    /**
     * Sets the value of the reloadBaseFAACode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReloadBaseFAACode(String value) {
        this.reloadBaseFAACode = value;
    }

    public boolean isSetReloadBaseFAACode() {
        return (this.reloadBaseFAACode!= null);
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequenceNumber(String value) {
        this.sequenceNumber = value;
    }

    public boolean isSetSequenceNumber() {
        return (this.sequenceNumber!= null);
    }

    /**
     * Gets the value of the quantityRequested property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQuantityRequested() {
        return quantityRequested;
    }

    /**
     * Sets the value of the quantityRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuantityRequested(Integer value) {
        this.quantityRequested = value;
    }

    public boolean isSetQuantityRequested() {
        return (this.quantityRequested!= null);
    }

    /**
     * Gets the value of the financialCode property.
     * 
     * @return
     *     possible object is
     *     {@link FinancialCodeType }
     *     
     */
    public FinancialCodeType getFinancialCode() {
        return financialCode;
    }

    /**
     * Sets the value of the financialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinancialCodeType }
     *     
     */
    public void setFinancialCode(FinancialCodeType value) {
        this.financialCode = value;
    }

    public boolean isSetFinancialCode() {
        return (this.financialCode!= null);
    }

    /**
     * Gets the value of the shippingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getShippingAddress() {
        return shippingAddress;
    }

    /**
     * Sets the value of the shippingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setShippingAddress(AddressType value) {
        this.shippingAddress = value;
    }

    public boolean isSetShippingAddress() {
        return (this.shippingAddress!= null);
    }

    /**
     * Gets the value of the shippingInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingInstructionsCreateType }
     *     
     */
    public ShippingInstructionsCreateType getShippingInstructions() {
        return shippingInstructions;
    }

    /**
     * Sets the value of the shippingInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingInstructionsCreateType }
     *     
     */
    public void setShippingInstructions(ShippingInstructionsCreateType value) {
        this.shippingInstructions = value;
    }

    public boolean isSetShippingInstructions() {
        return (this.shippingInstructions!= null);
    }

    /**
     * Gets the value of the willPickUpInfo property.
     * 
     * @return
     *     possible object is
     *     {@link WillPickUpInformationType }
     *     
     */
    public WillPickUpInformationType getWillPickUpInfo() {
        return willPickUpInfo;
    }

    /**
     * Sets the value of the willPickUpInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link WillPickUpInformationType }
     *     
     */
    public void setWillPickUpInfo(WillPickUpInformationType value) {
        this.willPickUpInfo = value;
    }

    public boolean isSetWillPickUpInfo() {
        return (this.willPickUpInfo!= null);
    }

    /**
     * Gets the value of the shippingContactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingContactName() {
        return shippingContactName;
    }

    /**
     * Sets the value of the shippingContactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingContactName(String value) {
        this.shippingContactName = value;
    }

    public boolean isSetShippingContactName() {
        return (this.shippingContactName!= null);
    }

    /**
     * Gets the value of the shippingContactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingContactPhone() {
        return shippingContactPhone;
    }

    /**
     * Sets the value of the shippingContactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingContactPhone(String value) {
        this.shippingContactPhone = value;
    }

    public boolean isSetShippingContactPhone() {
        return (this.shippingContactPhone!= null);
    }

    /**
     * Gets the value of the replacementInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReplacementInd() {
        return replacementInd;
    }

    /**
     * Sets the value of the replacementInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReplacementInd(Boolean value) {
        this.replacementInd = value;
    }

    public boolean isSetReplacementInd() {
        return (this.replacementInd!= null);
    }

    /**
     * Gets the value of the specialNeeds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialNeeds() {
        return specialNeeds;
    }

    /**
     * Sets the value of the specialNeeds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialNeeds(String value) {
        this.specialNeeds = value;
    }

    public boolean isSetSpecialNeeds() {
        return (this.specialNeeds!= null);
    }

}
