//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing filled resource request information returned to external systems
 * 
 * <p>Java class for ResourceRequestFilledReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceRequestFilledReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeResourceRequestKeyType"/>
 *         &lt;element name="RequestBase" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestBaseReturnType"/>
 *         &lt;element name="Assignment" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceAssignmentReturnType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceRequestFilledReturnType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "requestKey",
    "requestBase",
    "assignment"
})
public class ResourceRequestFilledReturnType {

    @XmlElement(name = "RequestKey", required = true)
    protected CompositeResourceRequestKeyType requestKey;
    @XmlElement(name = "RequestBase", required = true)
    protected ResourceRequestBaseReturnType requestBase;
    @XmlElement(name = "Assignment", required = true)
    protected ResourceAssignmentReturnType assignment;

    /**
     * Gets the value of the requestKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeResourceRequestKeyType }
     *     
     */
    public CompositeResourceRequestKeyType getRequestKey() {
        return requestKey;
    }

    /**
     * Sets the value of the requestKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeResourceRequestKeyType }
     *     
     */
    public void setRequestKey(CompositeResourceRequestKeyType value) {
        this.requestKey = value;
    }

    public boolean isSetRequestKey() {
        return (this.requestKey!= null);
    }

    /**
     * Gets the value of the requestBase property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRequestBaseReturnType }
     *     
     */
    public ResourceRequestBaseReturnType getRequestBase() {
        return requestBase;
    }

    /**
     * Sets the value of the requestBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRequestBaseReturnType }
     *     
     */
    public void setRequestBase(ResourceRequestBaseReturnType value) {
        this.requestBase = value;
    }

    public boolean isSetRequestBase() {
        return (this.requestBase!= null);
    }

    /**
     * Gets the value of the assignment property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceAssignmentReturnType }
     *     
     */
    public ResourceAssignmentReturnType getAssignment() {
        return assignment;
    }

    /**
     * Sets the value of the assignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceAssignmentReturnType }
     *     
     */
    public void setAssignment(ResourceAssignmentReturnType value) {
        this.assignment = value;
    }

    public boolean isSetAssignment() {
        return (this.assignment!= null);
    }

}
