//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing the resource attributes identifying an organization that provides resources
 * 
 * <p>Java class for ResourceOrganizationNaturalKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceOrganizationNaturalKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnitID" type="{http://nwcg.gov/services/ross/common_types/1.1}UnitIDType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceOrganizationNaturalKeyType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "unitID"
})
public class ResourceOrganizationNaturalKeyType {

    @XmlElement(name = "UnitID", required = true)
    protected UnitIDType unitID;

    /**
     * Gets the value of the unitID property.
     * 
     * @return
     *     possible object is
     *     {@link UnitIDType }
     *     
     */
    public UnitIDType getUnitID() {
        return unitID;
    }

    /**
     * Sets the value of the unitID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitIDType }
     *     
     */
    public void setUnitID(UnitIDType value) {
        this.unitID = value;
    }

    public boolean isSetUnitID() {
        return (this.unitID!= null);
    }

}
