//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Structure containing contact information for a resource request
 * 
 * <p>Java class for ResourceRequestContactReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceRequestContactReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ContactType" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestContactTypeSimpleType"/>
 *         &lt;element name="ContactInfo" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestContactInfoSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceRequestContactReturnType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "contactType",
    "contactInfo"
})
public class ResourceRequestContactReturnType {

    @XmlElement(name = "ContactType", required = true)
    protected ResourceRequestContactTypeSimpleType contactType;
    @XmlElement(name = "ContactInfo", required = true)
    protected String contactInfo;

    /**
     * Gets the value of the contactType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRequestContactTypeSimpleType }
     *     
     */
    public ResourceRequestContactTypeSimpleType getContactType() {
        return contactType;
    }

    /**
     * Sets the value of the contactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRequestContactTypeSimpleType }
     *     
     */
    public void setContactType(ResourceRequestContactTypeSimpleType value) {
        this.contactType = value;
    }

    public boolean isSetContactType() {
        return (this.contactType!= null);
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactInfo(String value) {
        this.contactInfo = value;
    }

    public boolean isSetContactInfo() {
        return (this.contactInfo!= null);
    }

}
