//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Structure Containing the assignment of a resource returned to external systems
 * 
 * <p>Java class for ResourceAssignmentReturnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResourceAssignmentReturnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ResourceKey" type="{http://nwcg.gov/services/ross/common_types/1.1}CompositeResourceKeyType" minOccurs="0"/>
 *         &lt;element name="MobilizationETD" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="MobilizationETA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="MobilizationATA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DemobilizationETD" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="DemobilizationETA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ResourceContact" type="{http://nwcg.gov/services/ross/common_types/1.1}PersonOrOrganizationContact" minOccurs="0"/>
 *         &lt;element name="FillDocumentation" type="{http://nwcg.gov/services/ross/common_types/1.1}DocumentationReturnType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AssigningContact" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceRequestContactReturnType" minOccurs="0"/>
 *         &lt;element name="QuantityAssigned" type="{http://nwcg.gov/services/ross/common_types/1.1}QuantitySimpleType" minOccurs="0"/>
 *         &lt;element name="AgreementNumber" type="{http://nwcg.gov/services/ross/common_types/1.1}AgreementNumberSimpleType" minOccurs="0"/>
 *         &lt;element name="OwnerName" type="{http://nwcg.gov/services/ross/common_types/1.1}OwnerNameSimpleType" minOccurs="0"/>
 *         &lt;element name="ProviderName" type="{http://nwcg.gov/services/ross/common_types/1.1}ProviderNameSimpleType" minOccurs="0"/>
 *         &lt;element name="EFFADContactInformation" type="{http://nwcg.gov/services/ross/common_types/1.1}EFFADContactInfoType" minOccurs="0"/>
 *         &lt;element name="CallSign" type="{http://nwcg.gov/services/ross/common_types/1.1}ResourceNameSimpleType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResourceAssignmentReturnType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "resourceKey",
    "mobilizationETD",
    "mobilizationETA",
    "mobilizationATA",
    "demobilizationETD",
    "demobilizationETA",
    "resourceContact",
    "fillDocumentation",
    "assigningContact",
    "quantityAssigned",
    "agreementNumber",
    "ownerName",
    "providerName",
    "effadContactInformation",
    "callSign"
})
public class ResourceAssignmentReturnType {

    @XmlElement(name = "ResourceKey")
    protected CompositeResourceKeyType resourceKey;
    @XmlElement(name = "MobilizationETD")
    protected XMLGregorianCalendar mobilizationETD;
    @XmlElement(name = "MobilizationETA")
    protected XMLGregorianCalendar mobilizationETA;
    @XmlElement(name = "MobilizationATA")
    protected XMLGregorianCalendar mobilizationATA;
    @XmlElement(name = "DemobilizationETD")
    protected XMLGregorianCalendar demobilizationETD;
    @XmlElement(name = "DemobilizationETA")
    protected XMLGregorianCalendar demobilizationETA;
    @XmlElement(name = "ResourceContact")
    protected PersonOrOrganizationContact resourceContact;
    @XmlElement(name = "FillDocumentation")
    protected List<DocumentationReturnType> fillDocumentation;
    @XmlElement(name = "AssigningContact")
    protected ResourceRequestContactReturnType assigningContact;
    @XmlElement(name = "QuantityAssigned")
    protected Integer quantityAssigned;
    @XmlElement(name = "AgreementNumber")
    protected String agreementNumber;
    @XmlElement(name = "OwnerName")
    protected String ownerName;
    @XmlElement(name = "ProviderName")
    protected String providerName;
    @XmlElement(name = "EFFADContactInformation")
    protected String effadContactInformation;
    @XmlElement(name = "CallSign")
    protected String callSign;

    /**
     * Gets the value of the resourceKey property.
     * 
     * @return
     *     possible object is
     *     {@link CompositeResourceKeyType }
     *     
     */
    public CompositeResourceKeyType getResourceKey() {
        return resourceKey;
    }

    /**
     * Sets the value of the resourceKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositeResourceKeyType }
     *     
     */
    public void setResourceKey(CompositeResourceKeyType value) {
        this.resourceKey = value;
    }

    public boolean isSetResourceKey() {
        return (this.resourceKey!= null);
    }

    /**
     * Gets the value of the mobilizationETD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMobilizationETD() {
        return mobilizationETD;
    }

    /**
     * Sets the value of the mobilizationETD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMobilizationETD(XMLGregorianCalendar value) {
        this.mobilizationETD = value;
    }

    public boolean isSetMobilizationETD() {
        return (this.mobilizationETD!= null);
    }

    /**
     * Gets the value of the mobilizationETA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMobilizationETA() {
        return mobilizationETA;
    }

    /**
     * Sets the value of the mobilizationETA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMobilizationETA(XMLGregorianCalendar value) {
        this.mobilizationETA = value;
    }

    public boolean isSetMobilizationETA() {
        return (this.mobilizationETA!= null);
    }

    /**
     * Gets the value of the mobilizationATA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMobilizationATA() {
        return mobilizationATA;
    }

    /**
     * Sets the value of the mobilizationATA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMobilizationATA(XMLGregorianCalendar value) {
        this.mobilizationATA = value;
    }

    public boolean isSetMobilizationATA() {
        return (this.mobilizationATA!= null);
    }

    /**
     * Gets the value of the demobilizationETD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDemobilizationETD() {
        return demobilizationETD;
    }

    /**
     * Sets the value of the demobilizationETD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDemobilizationETD(XMLGregorianCalendar value) {
        this.demobilizationETD = value;
    }

    public boolean isSetDemobilizationETD() {
        return (this.demobilizationETD!= null);
    }

    /**
     * Gets the value of the demobilizationETA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDemobilizationETA() {
        return demobilizationETA;
    }

    /**
     * Sets the value of the demobilizationETA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDemobilizationETA(XMLGregorianCalendar value) {
        this.demobilizationETA = value;
    }

    public boolean isSetDemobilizationETA() {
        return (this.demobilizationETA!= null);
    }

    /**
     * Gets the value of the resourceContact property.
     * 
     * @return
     *     possible object is
     *     {@link PersonOrOrganizationContact }
     *     
     */
    public PersonOrOrganizationContact getResourceContact() {
        return resourceContact;
    }

    /**
     * Sets the value of the resourceContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonOrOrganizationContact }
     *     
     */
    public void setResourceContact(PersonOrOrganizationContact value) {
        this.resourceContact = value;
    }

    public boolean isSetResourceContact() {
        return (this.resourceContact!= null);
    }

    /**
     * Gets the value of the fillDocumentation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fillDocumentation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFillDocumentation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentationReturnType }
     * 
     * 
     */
    public List<DocumentationReturnType> getFillDocumentation() {
        if (fillDocumentation == null) {
            fillDocumentation = new ArrayList<DocumentationReturnType>();
        }
        return this.fillDocumentation;
    }

    public boolean isSetFillDocumentation() {
        return ((this.fillDocumentation!= null)&&(!this.fillDocumentation.isEmpty()));
    }

    public void unsetFillDocumentation() {
        this.fillDocumentation = null;
    }

    /**
     * Gets the value of the assigningContact property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceRequestContactReturnType }
     *     
     */
    public ResourceRequestContactReturnType getAssigningContact() {
        return assigningContact;
    }

    /**
     * Sets the value of the assigningContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceRequestContactReturnType }
     *     
     */
    public void setAssigningContact(ResourceRequestContactReturnType value) {
        this.assigningContact = value;
    }

    public boolean isSetAssigningContact() {
        return (this.assigningContact!= null);
    }

    /**
     * Gets the value of the quantityAssigned property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getQuantityAssigned() {
        return quantityAssigned;
    }

    /**
     * Sets the value of the quantityAssigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setQuantityAssigned(Integer value) {
        this.quantityAssigned = value;
    }

    public boolean isSetQuantityAssigned() {
        return (this.quantityAssigned!= null);
    }

    /**
     * Gets the value of the agreementNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementNumber() {
        return agreementNumber;
    }

    /**
     * Sets the value of the agreementNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementNumber(String value) {
        this.agreementNumber = value;
    }

    public boolean isSetAgreementNumber() {
        return (this.agreementNumber!= null);
    }

    /**
     * Gets the value of the ownerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * Sets the value of the ownerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerName(String value) {
        this.ownerName = value;
    }

    public boolean isSetOwnerName() {
        return (this.ownerName!= null);
    }

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    public boolean isSetProviderName() {
        return (this.providerName!= null);
    }

    /**
     * Gets the value of the effadContactInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEFFADContactInformation() {
        return effadContactInformation;
    }

    /**
     * Sets the value of the effadContactInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEFFADContactInformation(String value) {
        this.effadContactInformation = value;
    }

    public boolean isSetEFFADContactInformation() {
        return (this.effadContactInformation!= null);
    }

    /**
     * Gets the value of the callSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSign() {
        return callSign;
    }

    /**
     * Sets the value of the callSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSign(String value) {
        this.callSign = value;
    }

    public boolean isSetCallSign() {
        return (this.callSign!= null);
    }

}
