//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-08/21/2008 01:11 PM(foreman)-fcs)
//


package gov.nwcg.services.ross.common_types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubstitutionLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstitutionLineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CatalogItem" type="{http://nwcg.gov/services/ross/common_types/1.1}CatalogItemNaturalKeyType"/>
 *         &lt;element name="Quantity" type="{http://nwcg.gov/services/ross/common_types/1.1}QuantitySimpleType"/>
 *         &lt;element name="UserDocumentation" type="{http://nwcg.gov/services/ross/common_types/1.1}DocumentationTextSimpleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstitutionLineType", namespace = "http://nwcg.gov/services/ross/common_types/1.1", propOrder = {
    "catalogItem",
    "quantity",
    "userDocumentation"
})
public class SubstitutionLineType {

    @XmlElement(name = "CatalogItem", required = true)
    protected CatalogItemNaturalKeyType catalogItem;
    @XmlElement(name = "Quantity")
    protected int quantity;
    @XmlElement(name = "UserDocumentation", required = true)
    protected String userDocumentation;

    /**
     * Gets the value of the catalogItem property.
     * 
     * @return
     *     possible object is
     *     {@link CatalogItemNaturalKeyType }
     *     
     */
    public CatalogItemNaturalKeyType getCatalogItem() {
        return catalogItem;
    }

    /**
     * Sets the value of the catalogItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link CatalogItemNaturalKeyType }
     *     
     */
    public void setCatalogItem(CatalogItemNaturalKeyType value) {
        this.catalogItem = value;
    }

    public boolean isSetCatalogItem() {
        return (this.catalogItem!= null);
    }

    /**
     * Gets the value of the quantity property.
     * 
     */
    public int getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     */
    public void setQuantity(int value) {
        this.quantity = value;
    }

    public boolean isSetQuantity() {
        return true;
    }

    /**
     * Gets the value of the userDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDocumentation() {
        return userDocumentation;
    }

    /**
     * Sets the value of the userDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDocumentation(String value) {
        this.userDocumentation = value;
    }

    public boolean isSetUserDocumentation() {
        return (this.userDocumentation!= null);
    }

}
