<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by Mark Carlson (LOCKHEED MARTIN INFO TECH) -->
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:nwcg="http://nwcg.gov/services/ross/common_types/1.1" xmlns:ro="http://nwcg.gov/services/ross/resource_order/1.1" xmlns:ron="http://nwcg.gov/services/ross/resource_order_notification/1.1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://nwcg.gov/services/ross/resource_order/wsdl/1.1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" name="ResourceOrder_WSDL" targetNamespace="http://nwcg.gov/services/ross/resource_order/wsdl/1.1">
	<types>
		<xs:schema xmlns:ns1="http://schemas.xmlsoap.org/soap/encoding/" version="1.1">
			<xs:import namespace="http://nwcg.gov/services/ross/resource_order/1.1" schemaLocation="ResourceOrder.xsd"/>
			<xs:import namespace="http://nwcg.gov/services/ross/resource_order_notification/1.1" schemaLocation="ResourceOrderNotification.xsd"/>			
			<xs:import namespace="http://nwcg.gov/services/ross/common_types/1.1" schemaLocation="RossCommon.xsd"/>
			<xs:import namespace="http://nwcg.gov/services/ross/catalog/1.1" schemaLocation="Catalog.xsd"/>
			<xs:import namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" schemaLocation="RossSecurity.xsd"/>
		</xs:schema>
	</types>
	<message name="DeliverOperationResultsReq">
		<part element="ro:DeliverOperationResultsReq" name="body"/>
	</message>
	<message name="DeliverOperationResultsResp">
		<part element="ro:DeliverOperationResultsResp" name="body"/>
	</message>
	<message name="DeliverNotificationReq">
		<part element="ron:DeliverNotificationReq" name="body"/>
	</message>
	<message name="DeliverNotificationResp">
		<part element="ron:DeliverNotificationResp" name="body"/>
	</message>
	<portType name="DeliveryInterface">
		<operation name="DeliverOperationResult">
			<input message="tns:DeliverOperationResultsReq"/>
			<output message="tns:DeliverOperationResultsResp"/>
		</operation>
		<operation name="DeliverNotification">
			<input message="tns:DeliverNotificationReq"/>
			<output message="tns:DeliverNotificationResp"/>
		</operation>
	</portType>
	<binding name="DeliveryBinding" type="tns:DeliveryInterface">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="DeliverOperationResult">
			<soap:operation soapAction="DeliverOperationResult" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
		<operation name="DeliverNotification">
			<soap:operation soapAction="DeliverNotificationt" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="DeliveryService">
		<port binding="tns:DeliveryBinding" name="DeliveryPort">
			<!-- <soap:address location="http://localhost:9080/ICBSROperations/DeliveryService"/> -->
			<soap:address location="http://localhost:9081/Operations/DeliveryService"/>
		</port>
	</service>
</definitions>
