CREATE TABLE OMCTMETA.EXEL_ORDER_EXTRACT_STEP3
  (
    "STATUS"                  CHAR(15),
    "STATUS_QUANTITY"         DECIMAL(14,4),
    "ORDER_HEADER_KEY"        CHAR(24),
    "ORDER_LINE_KEY"          CHAR(24),
    "ORDER_RELEASE_KEY"       CHAR(24),
    "ORDER_LINE_SCHEDULE_KEY" CHAR(24)
  )