truncate table SI_VERSION;
truncate table yfs_heartbeat;
truncate table yfs_statistics_detail;
DROP INDEX "ATTRIBUTE_I1";
CREATE UNIQUE INDEX "ATTRIBUTE_I1" ON "YFS_ATTRIBUTE" ("ATTRIBUTE_KEY","ATTRIBUTE_ID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "YFS";
Delete from SI_VERSION where PRODUCT_LABEL = 'Sterling WMS Add In';
Delete from SI_VERSION where PRODUCT_LABEL = 'Sterling WMS';
Insert into SI_VERSION (PRODUCT_LABEL,BUILD_NUMBER,LIC_PROD_VER,SI_INSTALL_DATE,SI_COMMENTS) values ('Sterling WMS Add In','9.1 (495)','9.1',to_date('05-FEB-14','DD-MON-RR'),'IBM Sterling Selling and Fulfillment Suite');
Insert into SI_VERSION (PRODUCT_LABEL,BUILD_NUMBER,LIC_PROD_VER,SI_INSTALL_DATE,SI_COMMENTS) values ('Sterling WMS','9.1 (495)','9.1',to_date('05-FEB-14','DD-MON-RR'),'IBM Sterling Selling and Fulfillment Suite');
