//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package gov.nwcg.services.ross.resource_order._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import gov.nwcg.services.ross.common_types._1.ResponseStatusType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nwcg.services.ross.resource_order._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetOperationResultsRespResponseStatus_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "ResponseStatus");
    private final static QName _DeliverOperationResultsReqDistributionID_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "DistributionID");
    private final static QName _UtfResourceRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "UtfResourceRequestResp");
    private final static QName _CreateIncidentAndRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "CreateIncidentAndRequestResp");
    private final static QName _PlaceResourceRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "PlaceResourceRequestResp");
    private final static QName _NotifyResourceRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "NotifyResourceRequestResp");
    private final static QName _FillResourceRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "FillResourceRequestResp");
    private final static QName _CreateIncidentRequestAndFillResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "CreateIncidentRequestAndFillResp");
    private final static QName _CreateResourceRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "CreateResourceRequestResp");
    private final static QName _CreateRequestAndFillResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "CreateRequestAndFillResp");
    private final static QName _CancelResourceRequestResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "CancelResourceRequestResp");
    private final static QName _CreateIncidentRequestAndPlaceResp_QNAME = new QName("http://nwcg.gov/services/ross/resource_order/1.1", "CreateIncidentRequestAndPlaceResp");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nwcg.services.ross.resource_order._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetIncidentRadioFrequenciesReq }
     * 
     */
    public GetIncidentRadioFrequenciesReq createGetIncidentRadioFrequenciesReq() {
        return new GetIncidentRadioFrequenciesReq();
    }

    /**
     * Create an instance of {@link ResourcesOperationResponseType }
     * 
     */
    public ResourcesOperationResponseType createResourcesOperationResponseType() {
        return new ResourcesOperationResponseType();
    }

    /**
     * Create an instance of {@link GetOperationResultsReq }
     * 
     */
    public GetOperationResultsReq createGetOperationResultsReq() {
        return new GetOperationResultsReq();
    }

    /**
     * Create an instance of {@link GetIncidentResp }
     * 
     */
    public GetIncidentResp createGetIncidentResp() {
        return new GetIncidentResp();
    }

    /**
     * Create an instance of {@link GetIncidentsRequestsByStatusReq }
     * 
     */
    public GetIncidentsRequestsByStatusReq createGetIncidentsRequestsByStatusReq() {
        return new GetIncidentsRequestsByStatusReq();
    }

    /**
     * Create an instance of {@link PlaceResourceRequestExternalResp }
     * 
     */
    public PlaceResourceRequestExternalResp createPlaceResourceRequestExternalResp() {
        return new PlaceResourceRequestExternalResp();
    }

    /**
     * Create an instance of {@link FillResourceRequestReq }
     * 
     */
    public FillResourceRequestReq createFillResourceRequestReq() {
        return new FillResourceRequestReq();
    }

    /**
     * Create an instance of {@link ReplaceIncidentRadioFrequenciesResp }
     * 
     */
    public ReplaceIncidentRadioFrequenciesResp createReplaceIncidentRadioFrequenciesResp() {
        return new ReplaceIncidentRadioFrequenciesResp();
    }

    /**
     * Create an instance of {@link AuthenticateUserReq }
     * 
     */
    public AuthenticateUserReq createAuthenticateUserReq() {
        return new AuthenticateUserReq();
    }

    /**
     * Create an instance of {@link GetIncidentAndRequestsReq }
     * 
     */
    public GetIncidentAndRequestsReq createGetIncidentAndRequestsReq() {
        return new GetIncidentAndRequestsReq();
    }

    /**
     * Create an instance of {@link GetIncidentAndRequestsResp }
     * 
     */
    public GetIncidentAndRequestsResp createGetIncidentAndRequestsResp() {
        return new GetIncidentAndRequestsResp();
    }

    /**
     * Create an instance of {@link StatusNFESResourceRequestReq }
     * 
     */
    public StatusNFESResourceRequestReq createStatusNFESResourceRequestReq() {
        return new StatusNFESResourceRequestReq();
    }

    /**
     * Create an instance of {@link UpdateNFESResourceRequestReq }
     * 
     */
    public UpdateNFESResourceRequestReq createUpdateNFESResourceRequestReq() {
        return new UpdateNFESResourceRequestReq();
    }

    /**
     * Create an instance of {@link RetrieveResourceRequestReq }
     * 
     */
    public RetrieveResourceRequestReq createRetrieveResourceRequestReq() {
        return new RetrieveResourceRequestReq();
    }

    /**
     * Create an instance of {@link UpdateIncidentDetailsResp }
     * 
     */
    public UpdateIncidentDetailsResp createUpdateIncidentDetailsResp() {
        return new UpdateIncidentDetailsResp();
    }

    /**
     * Create an instance of {@link StatusNFESResourceRequestResp }
     * 
     */
    public StatusNFESResourceRequestResp createStatusNFESResourceRequestResp() {
        return new StatusNFESResourceRequestResp();
    }

    /**
     * Create an instance of {@link GetIncidentRadioFrequenciesResp }
     * 
     */
    public GetIncidentRadioFrequenciesResp createGetIncidentRadioFrequenciesResp() {
        return new GetIncidentRadioFrequenciesResp();
    }

    /**
     * Create an instance of {@link CreateIncidentRequestAndPlaceReq }
     * 
     */
    public CreateIncidentRequestAndPlaceReq createCreateIncidentRequestAndPlaceReq() {
        return new CreateIncidentRequestAndPlaceReq();
    }

    /**
     * Create an instance of {@link ReplaceIncidentRadioFrequenciesReq }
     * 
     */
    public ReplaceIncidentRadioFrequenciesReq createReplaceIncidentRadioFrequenciesReq() {
        return new ReplaceIncidentRadioFrequenciesReq();
    }

    /**
     * Create an instance of {@link AuthenticateUserResp }
     * 
     */
    public AuthenticateUserResp createAuthenticateUserResp() {
        return new AuthenticateUserResp();
    }

    /**
     * Create an instance of {@link CreateResourceRequestReq }
     * 
     */
    public CreateResourceRequestReq createCreateResourceRequestReq() {
        return new CreateResourceRequestReq();
    }

    /**
     * Create an instance of {@link ResourceOrderResponseType }
     * 
     */
    public ResourceOrderResponseType createResourceOrderResponseType() {
        return new ResourceOrderResponseType();
    }

    /**
     * Create an instance of {@link RegisterIncidentInterestReq }
     * 
     */
    public RegisterIncidentInterestReq createRegisterIncidentInterestReq() {
        return new RegisterIncidentInterestReq();
    }

    /**
     * Create an instance of {@link RetrieveResourceRequestResp }
     * 
     */
    public RetrieveResourceRequestResp createRetrieveResourceRequestResp() {
        return new RetrieveResourceRequestResp();
    }

    /**
     * Create an instance of {@link CreateIncidentAndRequestReq }
     * 
     */
    public CreateIncidentAndRequestReq createCreateIncidentAndRequestReq() {
        return new CreateIncidentAndRequestReq();
    }

    /**
     * Create an instance of {@link IncidentOperationResponseType }
     * 
     */
    public IncidentOperationResponseType createIncidentOperationResponseType() {
        return new IncidentOperationResponseType();
    }

    /**
     * Create an instance of {@link PlaceResourceRequestReq }
     * 
     */
    public PlaceResourceRequestReq createPlaceResourceRequestReq() {
        return new PlaceResourceRequestReq();
    }

    /**
     * Create an instance of {@link CreateRequestAndFillReq }
     * 
     */
    public CreateRequestAndFillReq createCreateRequestAndFillReq() {
        return new CreateRequestAndFillReq();
    }

    /**
     * Create an instance of {@link SetIncidentActivationReq }
     * 
     */
    public SetIncidentActivationReq createSetIncidentActivationReq() {
        return new SetIncidentActivationReq();
    }

    /**
     * Create an instance of {@link RegisterIncidentInterestResp }
     * 
     */
    public RegisterIncidentInterestResp createRegisterIncidentInterestResp() {
        return new RegisterIncidentInterestResp();
    }

    /**
     * Create an instance of {@link CreateRequestAndPlaceResp }
     * 
     */
    public CreateRequestAndPlaceResp createCreateRequestAndPlaceResp() {
        return new CreateRequestAndPlaceResp();
    }

    /**
     * Create an instance of {@link UtfResourceRequestReq }
     * 
     */
    public UtfResourceRequestReq createUtfResourceRequestReq() {
        return new UtfResourceRequestReq();
    }

    /**
     * Create an instance of {@link CreateIncidentReq }
     * 
     */
    public CreateIncidentReq createCreateIncidentReq() {
        return new CreateIncidentReq();
    }

    /**
     * Create an instance of {@link UpdateIncidentDetailsReq }
     * 
     */
    public UpdateIncidentDetailsReq createUpdateIncidentDetailsReq() {
        return new UpdateIncidentDetailsReq();
    }

    /**
     * Create an instance of {@link CancelResourceRequestReq }
     * 
     */
    public CancelResourceRequestReq createCancelResourceRequestReq() {
        return new CancelResourceRequestReq();
    }

    /**
     * Create an instance of {@link DeliverOperationResultsReq }
     * 
     */
    public DeliverOperationResultsReq createDeliverOperationResultsReq() {
        return new DeliverOperationResultsReq();
    }

    /**
     * Create an instance of {@link UpdateIncidentNumberResp }
     * 
     */
    public UpdateIncidentNumberResp createUpdateIncidentNumberResp() {
        return new UpdateIncidentNumberResp();
    }

    /**
     * Create an instance of {@link CreateRequestAndPlaceReq }
     * 
     */
    public CreateRequestAndPlaceReq createCreateRequestAndPlaceReq() {
        return new CreateRequestAndPlaceReq();
    }

    /**
     * Create an instance of {@link GetResourceRequestReq }
     * 
     */
    public GetResourceRequestReq createGetResourceRequestReq() {
        return new GetResourceRequestReq();
    }

    /**
     * Create an instance of {@link GetIncidentAviationHazardsResp }
     * 
     */
    public GetIncidentAviationHazardsResp createGetIncidentAviationHazardsResp() {
        return new GetIncidentAviationHazardsResp();
    }

    /**
     * Create an instance of {@link UpdateIncidentStatusReq }
     * 
     */
    public UpdateIncidentStatusReq createUpdateIncidentStatusReq() {
        return new UpdateIncidentStatusReq();
    }

    /**
     * Create an instance of {@link CombinationResourceOrderResponseType }
     * 
     */
    public CombinationResourceOrderResponseType createCombinationResourceOrderResponseType() {
        return new CombinationResourceOrderResponseType();
    }

    /**
     * Create an instance of {@link CreateIncidentResp }
     * 
     */
    public CreateIncidentResp createCreateIncidentResp() {
        return new CreateIncidentResp();
    }

    /**
     * Create an instance of {@link CreateIncidentRequestAndFillReq }
     * 
     */
    public CreateIncidentRequestAndFillReq createCreateIncidentRequestAndFillReq() {
        return new CreateIncidentRequestAndFillReq();
    }

    /**
     * Create an instance of {@link GetResourceRequestResp }
     * 
     */
    public GetResourceRequestResp createGetResourceRequestResp() {
        return new GetResourceRequestResp();
    }

    /**
     * Create an instance of {@link ReplaceIncidentAviationHazardsResp }
     * 
     */
    public ReplaceIncidentAviationHazardsResp createReplaceIncidentAviationHazardsResp() {
        return new ReplaceIncidentAviationHazardsResp();
    }

    /**
     * Create an instance of {@link GetIncidentsRequestsByStatusResp }
     * 
     */
    public GetIncidentsRequestsByStatusResp createGetIncidentsRequestsByStatusResp() {
        return new GetIncidentsRequestsByStatusResp();
    }

    /**
     * Create an instance of {@link GetIncidentAviationHazardsReq }
     * 
     */
    public GetIncidentAviationHazardsReq createGetIncidentAviationHazardsReq() {
        return new GetIncidentAviationHazardsReq();
    }

    /**
     * Create an instance of {@link SetIncidentActivationResp }
     * 
     */
    public SetIncidentActivationResp createSetIncidentActivationResp() {
        return new SetIncidentActivationResp();
    }

    /**
     * Create an instance of {@link AddIncidentDocumentationResp }
     * 
     */
    public AddIncidentDocumentationResp createAddIncidentDocumentationResp() {
        return new AddIncidentDocumentationResp();
    }

    /**
     * Create an instance of {@link UpdateNFESResourceRequestResp }
     * 
     */
    public UpdateNFESResourceRequestResp createUpdateNFESResourceRequestResp() {
        return new UpdateNFESResourceRequestResp();
    }

    /**
     * Create an instance of {@link PlaceResourceRequestExternalReq }
     * 
     */
    public PlaceResourceRequestExternalReq createPlaceResourceRequestExternalReq() {
        return new PlaceResourceRequestExternalReq();
    }

    /**
     * Create an instance of {@link ReplaceIncidentAviationHazardsReq }
     * 
     */
    public ReplaceIncidentAviationHazardsReq createReplaceIncidentAviationHazardsReq() {
        return new ReplaceIncidentAviationHazardsReq();
    }

    /**
     * Create an instance of {@link UpdateIncidentStatusResp }
     * 
     */
    public UpdateIncidentStatusResp createUpdateIncidentStatusResp() {
        return new UpdateIncidentStatusResp();
    }

    /**
     * Create an instance of {@link CreateIncidentOperationResponseType }
     * 
     */
    public CreateIncidentOperationResponseType createCreateIncidentOperationResponseType() {
        return new CreateIncidentOperationResponseType();
    }

    /**
     * Create an instance of {@link GetIncidentReq }
     * 
     */
    public GetIncidentReq createGetIncidentReq() {
        return new GetIncidentReq();
    }

    /**
     * Create an instance of {@link GetIncidentDocumentationReq }
     * 
     */
    public GetIncidentDocumentationReq createGetIncidentDocumentationReq() {
        return new GetIncidentDocumentationReq();
    }

    /**
     * Create an instance of {@link UpdateIncidentNumberReq }
     * 
     */
    public UpdateIncidentNumberReq createUpdateIncidentNumberReq() {
        return new UpdateIncidentNumberReq();
    }

    /**
     * Create an instance of {@link DeliverOperationResultsResp }
     * 
     */
    public DeliverOperationResultsResp createDeliverOperationResultsResp() {
        return new DeliverOperationResultsResp();
    }

    /**
     * Create an instance of {@link NotifyResourceRequestReq }
     * 
     */
    public NotifyResourceRequestReq createNotifyResourceRequestReq() {
        return new NotifyResourceRequestReq();
    }

    /**
     * Create an instance of {@link AddIncidentDocumentationReq }
     * 
     */
    public AddIncidentDocumentationReq createAddIncidentDocumentationReq() {
        return new AddIncidentDocumentationReq();
    }

    /**
     * Create an instance of {@link GetOperationResultsResp }
     * 
     */
    public GetOperationResultsResp createGetOperationResultsResp() {
        return new GetOperationResultsResp();
    }

    /**
     * Create an instance of {@link GetIncidentDocumentationResp }
     * 
     */
    public GetIncidentDocumentationResp createGetIncidentDocumentationResp() {
        return new GetIncidentDocumentationResp();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "ResponseStatus", scope = GetOperationResultsResp.class)
    public JAXBElement<ResponseStatusType> createGetOperationResultsRespResponseStatus(ResponseStatusType value) {
        return new JAXBElement<ResponseStatusType>(_GetOperationResultsRespResponseStatus_QNAME, ResponseStatusType.class, GetOperationResultsResp.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "DistributionID", scope = DeliverOperationResultsReq.class)
    public JAXBElement<String> createDeliverOperationResultsReqDistributionID(String value) {
        return new JAXBElement<String>(_DeliverOperationResultsReqDistributionID_QNAME, String.class, DeliverOperationResultsReq.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "UtfResourceRequestResp")
    public JAXBElement<ResourceOrderResponseType> createUtfResourceRequestResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_UtfResourceRequestResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CombinationResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "CreateIncidentAndRequestResp")
    public JAXBElement<CombinationResourceOrderResponseType> createCreateIncidentAndRequestResp(CombinationResourceOrderResponseType value) {
        return new JAXBElement<CombinationResourceOrderResponseType>(_CreateIncidentAndRequestResp_QNAME, CombinationResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "PlaceResourceRequestResp")
    public JAXBElement<ResourceOrderResponseType> createPlaceResourceRequestResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_PlaceResourceRequestResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "NotifyResourceRequestResp")
    public JAXBElement<ResourceOrderResponseType> createNotifyResourceRequestResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_NotifyResourceRequestResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "FillResourceRequestResp")
    public JAXBElement<ResourceOrderResponseType> createFillResourceRequestResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_FillResourceRequestResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CombinationResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "CreateIncidentRequestAndFillResp")
    public JAXBElement<CombinationResourceOrderResponseType> createCreateIncidentRequestAndFillResp(CombinationResourceOrderResponseType value) {
        return new JAXBElement<CombinationResourceOrderResponseType>(_CreateIncidentRequestAndFillResp_QNAME, CombinationResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "CreateResourceRequestResp")
    public JAXBElement<ResourceOrderResponseType> createCreateResourceRequestResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_CreateResourceRequestResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "CreateRequestAndFillResp")
    public JAXBElement<ResourceOrderResponseType> createCreateRequestAndFillResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_CreateRequestAndFillResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "CancelResourceRequestResp")
    public JAXBElement<ResourceOrderResponseType> createCancelResourceRequestResp(ResourceOrderResponseType value) {
        return new JAXBElement<ResourceOrderResponseType>(_CancelResourceRequestResp_QNAME, ResourceOrderResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CombinationResourceOrderResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://nwcg.gov/services/ross/resource_order/1.1", name = "CreateIncidentRequestAndPlaceResp")
    public JAXBElement<CombinationResourceOrderResponseType> createCreateIncidentRequestAndPlaceResp(CombinationResourceOrderResponseType value) {
        return new JAXBElement<CombinationResourceOrderResponseType>(_CreateIncidentRequestAndPlaceResp_QNAME, CombinationResourceOrderResponseType.class, null, value);
    }

}
